== Урок 2. «ВЕДЫ – ИСТОЧНИК ИСТИННОГО ЗНАНИЯ»

[.lead]
Что это за знание, которое способно так благотворно повлиять на мою жизнь и существует ли оно вообще? Кто является источником этого Абсолютного знания, и каким способом его можно получить?

Существуют различные способы познания мира. Человек исследует его, задает вопросы родителям, учится в школе и других учебных заведениях, читает книги и газеты, смотрит телевизор, думает и размышляет над окружающим, испытывает озарения и т.п. Можно перечислить сотни путей приобретения знания. Но все эти пути можно свести к трем:

1. Пратьякша-прамана – Это способ получения знания через контакт с объектами внешнего мира посредством органов чувств.

1. Анумана-прамана – Это выдвижение гипотез на основании знаний, полученных в результате непосредственного восприятия («Может быть, это было так, но вполне возможно, что было иначе»).

1. Шабда-прамана – Получение знание через слушание из авторитетного источника.

[.lead]
В какой же мере применимы эти методы в познании Абсолютной Истины (истины, которая не меняется под влиянием места, времени и обстоятельств)?

Первый и второй способы получения знания позволяют получить только ограниченное знание, поскольку человек обладает следующими четырьмя недостатками:

1. Несовершенство чувств  

1. Склонность впадать в иллюзию

1. Склонность совершать ошибки

1. Склонность к обману

Итак, _пратьякша-прамана_, не годится для получения Абсолютного знания, поскольку наши чувства несовершенны. _Анумана-прамана_, также не подходит для этого, поскольку ум выдвигает гипотезы на основании знания, полученного через восприятие мира несовершенными чувствами, да и логика ума содержит изъяны, ведь человек имеет склонности впадать в иллюзию, совершать ошибки и обманывать. Методы _пратьякша_ и _анумана_ человек может использовать в обычной бытовой жизни, но чтобы получить знание, выходящее за пределы ограниченных чувств и ума, необходимо обратиться к _шабда-прамане_, то есть, услышать его от истинного авторитета. Например, если вы хотите узнать, кто ваш отец, вы должны обратиться к матери, и она точно назовет его. В противном случае, вы потратите огромное количество времени, разыскивая его своими силами, но так и не найдете его.

Таким образом, единственный способ познать объекты, находящиеся за пределами нашего восприятия – метод _шабда-прамана_ – «слушание из авторитетного источника». Поэтому получить знание Абсолютной Истины можно только воспользовавшись этим методом.

[.lead]
Но кто же является этим высшим авторитетом, источником Абсолютного знания?

Несомненно, высшим авторитетом может быть только тот, кто является совершенным. Люди называют такой высший авторитет Богом. Свободный от несовершенств, Он может передавать несовершенным живым существам Абсолютное знание. Получив такое знание, полную информацию об Абсолютной Истине, мы сможем увидеть мир в истинном свете и правильно оценивать события, происходящие с нами. Так наши действия станут безупречными, и мы достигнем истинного счастья, к которому так стремимся.

Знание, исходящее от Самого Бога, называют _апаурушея_ – «сверхчеловеческое».

[.lead]
Каковы признаки знания, относящегося к категории _апаурушея_?

Знание, изошедшее от Бога, должно обладать следующими характеристиками:

- Вечность, неизменность и совершенство. Обычное человеческое знание постоянно меняется, поскольку людям присущи недостатки, присущие их ограниченной природе. Но Господь всесовершенен, поэтому и знание, данное Им, вечно и совершенно. Следовательно, оно должно быть одинаково приложимо для разных народов, культур, традиций и актуально во все времена. Другими словами оно не «устаревает».
- Полнота и непротиворечивость. Это знание должно обладать законченностью и полнотой, т.е. оно должно быть практично и с духовной и с материальной точек зрения и описывать постепенный путь духовного очищения и возвышения человека и при этом учить людей удовлетворять повседневные материальные потребности. 
- Содержит доказательства своего Божественного происхождения. Поскольку нет авторитета выше Бога, знание, изошедшее от Него, должно содержать в себе доказательства своего Божественного происхождения.
- Это знание должно передаваться по цепи учителей, начинающейся от Самого Бога. Это необходимое условия для того, чтобы сохранить знание в неизменном виде.
- Подтверждается на практике. Применяя на практике это знание, человек может убедиться, что все, что он узнал, является истиной. 
- Подтверждается мудрецами, достигшими совершенства.
- Веды – это самоочевидное свидетельство. Другими словами, постигая Веды в правильном процессе познания каждому станет очевидна их истинность.

Очень многие святые прошлого, такие как Брахма (первое живое существо во Вселенной), Нарада Муни, Вьясадева, Мадхавачарья, Шанкарачарья, Рамануджа, Шри Чайтанья Махапрабху и многие другие, признавали «Ведическое знание» (или просто «Веды»), таким всесовершенным знанием, относящимся к категории _апаурушейа_. «Веды» сравнивают с «очками», помогающими «близорукому» живому существу увидеть истинную реальность.

[.lead]
Где в Ведической литературе подтверждается то, что Веды поведаны Самим Богом?

- В Шримад-Бхагаватам (11.14.3) сам Господь рассказывает о том, как Он, еще в самом начале творения Вселенной, поведал это Ведическое знание первому сотворенному живому существу Господу Брахме:

«Верховная Личность Бога сказал: Под влиянием времени, во время разрушения Вселенной, трансцендентные звуки Ведического знания были потеряны. Поэтому, когда началось следующее творение, Я заново поведал Ведическое знание Брахме, поскольку Я Сам являюсь олицетворением религиозных принципов, как о том утверждается в Ведах».

- В Бхагавад-гите (15.15) Господь говорит о предназначении данной Им Ведической литературы:

сарвасйа чха хди саннивишо +
матта смтир джнам апохана ча +
ведаи ча сарваир ахам эва ведйо +
веднта-кд веда-вид эва чхам +

«Я пребываю в сердце каждого живого существа, и от Меня исходят память, знание и забвение. Цель всех Вед – постичь Меня. Я – истинный составитель «Веданты» и знаток всех Вед».

Итак, Верховный Господь, являющийся источником всех духовных и материальных миров, сообщает нам, что Ведическое знание дано Им Самим. Воспользовавшись этим знанием, человек может постичь Абсолютную Истину, такой как она есть, и обрести высшее совершенство жизни.

[.lead]
Как же получить это Ведическое знание?