== Урок 7. РАЗНОВИДНОСТИ ДУХОВНЫХ УЧИТЕЛЕЙ

[.lead]
Сколько духовных учителей может быть у человека? Каковы их разновидности и что за функции они выполняют по отношению к ученику? Каков этикет общения с ними?

Прежде всего, необходимо отметить, что поскольку Господь существовал еще до появления других учителей, Его славят как Изначального Духовного Учителя, и только Он обладает самым полным, совершенным знанием. От Него исходит послание заблудшим детям Его, с помощью которого они могут вновь вернуться в запредельный мир блаженства. Все остальные учители являются Его представителями. Их функция заключается в том, чтобы передавать трансцендентное знание без искажения, с целью вернуть обусловленные души домой, к Богу. Поэтому их называют _шикша-гуру_, — духовные учители (_гуру_ – «тяжелый», т.е. полон духовного знания), передающие _шикшу_ (духовное знание).

Хотя роль всех учителей – передавать духовное знание (поэтому все они _шикша-гуру_), тем не менее, поскольку разные учители исполняют разные функции в этом процессе, их называют по-разному:

Сампрадая-гуру или Ади-гуру – основатель цепи ученической преемственности (сампрадаи). Ади-гуру получает знание непосредственно от Верховного Господа и передает его своим ученикам. Примерами ади-гуру являются Брахма, Шива, Кумары и Лакшми.

Ачарья-основатель – духовный учитель, исправляющий противоречия, возникающие в учении, и задающий новое направление миссии. Такой духовный учитель является особым преданным, которого направляет и уполномочивает Сам Господь. Примерами ачарий-основателей являются Шри Рамануджа, Шри Мадхава и, в недавнем прошлом, Шрила Прабхупада. Ачарья-основатель – это шикша-гуру для всех, кто за ним следует. Поэтому нарушать его указания или искажать его учение ни в коем случае нельзя.

Вартма-прадаршака-гуру – духовный учитель, который указывает путь. Это тот, кто впервые указывает человеку правильный путь к Богу.

Шикша-гуру – духовный учитель, дающий наставления, на основании Священных писаний.

Дикша-гуру – духовный учитель, дающий посвящение в цепи ученической преемственности.

Санньяса-гуру – духовный учитель, дающий санньясу (посвящение в отрешённость).

Все эти разновидности учителей выполняют различные функции в процессе передачи духовного знания. Все они являются уполномоченными представителями Бога, через которых Он проявляет Свое бесконечное милосердие по отношению к обусловленным душам, освобождая их из цепей неведения. Поэтому всем этим духовным учителям необходимо оказывать почтение. Пренебрежение или оскорбление по их адресу являются серьезными препятствиями на духовном пути. И по тому, как ученик относится к ним, можно судить о его отношении к Богу.

Как же Господь помогает душе обрести духовное знание через посредство всех этих учителей?

В начале Господь лично наставляет основателя цепи ученической преемственности (ади-гуру), который передает это знание своему ученику, а тот, в свою очередь, своему. Так это знание передается от учителя к ученику в неискаженном виде. 

Если из-за пагубного влияния этого века происходит какое-то искажение учения или его недопонимание, тогда Господь направляет Своего особого преданного ачарью-основателя, который исправляет учение и объясняет как применять его в условиях современности. Совсем недавно эту задачу выполнил Его Божественная Милость А.Ч. Бхактиведанта Свами Прабхупада, изложив сокровенное божественное знание на английском языке и распространив его по всему миру. В соответствии с предсказаниями, эти книги будут являться законами для всего человечества еще на протяжении 10000 лет, давая искренним людям возможность достичь духовного совершенства. 

Человек, запутавшийся в этом мире, встречается с вартма-прадаршака-гуру, через посредство которого Господь указывает ему путь к Себе и встреча с которым, становится причиной изменения его жизни. 

Затем ищущий Бога человек вступает в общение с преданными Богу людьми, которые, играя роль шикша-гуру (духовных наставников), воспитывают и наставляют ученика в процессе развития его преданности. 

Из всех шикша-гуру (наставляющих учителей) тот, чьи наставления значительней всего воодушевляют ученика на духовное совершенствование, обычно становится его дикша-гуру (духовный учитель, дающий посвящение в цепи ученической преемственности). Он принимает на себя обязательство за спасение ученика.

Затем следуют другие шикша-гуру, продолжающие его обучение.

Поскольку больше всего в своей духовной жизни ученик соприкасается с _дикша_ и _шикша-гуру_, будет полезным подробнее описать их:

«…_Дикша-гуру_ бывает один, и является «изначальным» или «настоящим» духовным учителем. _Шикша-гуру_ может быть много, — они подкрепляют наставления _дикша-гуру_, и исполняют подчиненную роль. _Шикша-гуру_ являются как бы двойниками _дикша-гуру_ (представитель и часть его тела), тесно взаимодействующими с ним. Их функция – привести потенциального ученика к _дикша-гуру_. _Дикша-гуру_ также может действовать в роли наставника, но это не обязательно.

Различия между _дикша-_ и _шикша-гуру_ определяются тем, какие обязанности они исполняют, однако, это, безусловно, не должно становиться причиной нездоровой мирской склонности унижать других. Поэтому ученик обязан слушаться наставников так же, как и своего _дикша-гуру_. Ученику надо научиться видеть, что в форме одного _дикша-гуру_ и многих _шикша-гуру_ перед ним воплотился Сам Верховный Господь. В этом заключается их единство. В то же время, не отвергая их онтологического равенства, ему следует знать, что каждый из них исполняет свои функции…».

(Шиварама Свами в книге «Шикша-гуру»)

Как правильно выбирать духовного учителя?

«Выбор _дикша-гуру_ – это серьезный шаг в жизни ученика. Чрезвычайно важно отнестись к этому выбору со всей серьезностью. «Скороспелое» влечение к _гуру_ может оказаться слишком шаткой опорой во взаимоотношениях с ним, в сравнении с пониманием духовного учителя, приобретенным в результате слушания и продолжительного общения. Поскольку всем обусловленным душам присуща тенденция совершать ошибки, следует делать свой выбор с большой осторожностью, основываясь на наставлениях Священных писаний. Начальную привязанность могут осквернять различные мирские представления, и потому она не может служить единственной опорой для принятия окончательного решения. Примерами таких второстепенных факторов, на которых может основываться искаженное влечение, являются дружелюбная манера общения, личное обаяние, харизма _гуру_, его таланты (например, красивое пение) или остроумные лекции. В выборе духовного учителя нужно, прежде всего, смотреть на то, насколько он сам следует своим _гуру_ и _ачарье-основателю_. Привязанность, основанная на внешних качествах, не имеет под собой духовной основы и может надолго стать причиной трудностей для ученика».

В каком случае ученик может отвергнуть духовного учителя?

Духовного учителя можно отвергнуть, если он падает из-за потворства своим чувствам, становится _майявади_ (провозглашает себя Богом) или оскорбляет предавшихся Богу людей. От _гуру_ следует отказаться также, если он совершает дурные поступки, скрываясь под маской преданного.

Если ученик отказывается от _дикша-гуру_ по любым другим причинам, он совершает серьезное оскорбление, которое приведет его к падению. Прежде чем принять решение отвергнуть духовного учителя, ученик должен сначала подойти к старшим преданным и, в смиренном состоянии сознания поделившись своим сомнением, попросить совета.

Таким образом Верховный Господь через посредство различных духовных учителей помогает обусловленной душе достичь высшего совершенства жизни.

Кто же этот изначальный Верховный Господь, обладающий самым полным, совершенным знанием? Является ли Он личностью или же Он безличен?