= Урок 1. ПУТЬ ВГЛУБЬ СЕБЯ

== Весь мир движется только благодаря одному, порой неявному, стремлению человека, — что же это за стремление?

Несомненно, это желание быть счастливым. Стремление к счастью является, наверное, самой глубинной и фундаментальной отличительной особенностью каждого человека, вне зависимости от его расовых или национальных характеристик, а также мировоззрения, религиозных или политических убеждений, социального статуса и т.д. И хотя способов, которыми человек пытается удовлетворить себя — бесчисленное множество, однако характер или природа этого стремления – едины для всех... Некоторые ищут счастья посредством логики, иные — посредством тайных сил йоги; некоторые отрекаются от мира и уходят в одиночество, другие постоянно ведут войну; иные устремляются в погоню за женщинами и богатством, кого-то увлекает искусство, кто-то выбирает науки.

Однако, несмотря на то, что все люди стремятся к счастью, оно, как правило, остается для них недостижимой мечтой. Чтобы обрести его, человек ставит перед собой всё новые и новые цели. Но, даже достигнув очередной своей цели, он не испытывает того счастья, которое предвкушал, и потому ставит новую цель. Так и проходит вся его жизнь в погоне за воображаемым счастьем. В какой-то момент по-настоящему разумный человек начинает задумываться: «Что-то не так. Почему я вынужден страдать, несмотря на то, что я не стремлюсь к страданиям? Кто виновен в этом? И в чём же истинный смысл и предназначение моей жизни?»

В соответствии с древней мудростью, именно способностью задавать такие вопросы и отличается человек от животных, которые никогда о подобных вещах не задумываются. В Ведах (_Хитопадеша_) говорится:

[quote, Хиттопадеша, HK]
--
AhAra-nidrA-bhaya-maithunaM ca +
samAnametatpazubhirnarANAm | +
dharmo hi teSAmadhiko vizeSo +
dharmeNa hInAH pazubhiH samAnAH ||
--

**пословный перевод:** 

AhAra - еда, процесс принятия пищи;
nidrA - сон;
bhaya - страх; 
maithunaM - совокупление;
ca - and;
samAnam - равное, одинаковое;
etat - это;
pashubhir ->  pashubhiH : [как] животными

[TIP]
pashu -> этимология слова : pAsha -> сеть, pashu -> тот кто находиться в сетях [иллюзии и привязан к материи] поскольку его не интересует духовное развитие.

narANAm - людей, т.е. люди и животные занимаются такой же деятельностью.

dharmo -> dharmaH - правильное поведение
hi - только
teShAm = их (людей)
adhiko -> adhikaH - более, в избытке
visheSho -> visheShaH - Отличается, используется для выделения из других, характеризует
dharmeNa hInAH -> без дхармы
pashubhiH -> [как] животными
samAnAH -> похожие
[quote, Хитопадеша]
--
«Такие виды деятельности, как еда, сон, совокупление и оборона, присущи как животным, так и людям. Человек считается выше животного только тогда, когда он вопрошает об Абсолютной Истине, в противном случае он ничем от животного не отличается».
--

Кто-то может возразить: «А я не страдаю, у меня всё отлично!» Но так ли это на самом деле? Разве мы не испытываем страдания от:

1. Беспокойств, приходящих к нам от сил природы (жара или холод, проливные дожди или засуха, стихийные бедствия и пр.);
2. Беспокойств, причиняемых нам другими живыми существами (насекомыми-паразитами, животными и птицами, а также растениями, ну и, конечно же, людьми);
3. Беспокойств, причиняемых собственным телом и умом (болезни тела, психические расстройства, стрессы и пр.).

Несомненно, все это присутствует в нашей жизни. Просто мы привыкли к этим страданиям, и принимаем их как что-то само собой разумеющееся и смирились с тем, что избавиться от них не в наших силах. Даже если в какой-то момент времени мы свободны от всех перечисленных выше неприятностей, они в любой момент могут к нам вернуться в той или иной форме – и понимание этого рождает в нас опасения и беспокойства, лишающие нас удовлетворения. Желая сохранить надежду на счастье, мы пытаемся быть оптимистами и просто приспосабливаемся к новым обстоятельствам. Но разумно ли это? Как лягушка, пытаясь приспособиться к нагреваемой воде, в конце концов, сварилась в ней — так и человек, который развил в себе привычку приспосабливаться ко всему, не задумываясь над глубинной причиной своих страданий, потерпит в своей жизни крах.

**Таким образом, мы подошли к необходимости сформулировать фундаментальное противоречие, ОБЪЕКТИВНО присутствующее в жизни каждого человека — противоречие между стремлением человека к счастью, с одной стороны, и беспокойствами, неизменно препятствующими достижению человеком этого состояния, с другой стороны (назовём это противоречие для удобства определения «_главным жизненным противоречием_»).**

**Это же противоречие объективно закладывает в человеке потребность искать выход из складывающегося безнадёжного положения, то есть, искать смысл жизни, поскольку человеческое сознание всегда будет вольно или невольно стремиться к преодолению того несчастливого существования, которое обусловлено этим «_главным жизненным противоречием_».**

Итак, будучи людьми, обладающими разумом, мы можем попытаться выяснить причину страданий и найти способ избавления от них.

== Где же коренится глубинная причина страданий человека? Почему разные люди испытывают различные страдания? От чего зависит течение жизни человека?



Есть такая пословица: _«Посеешь мысль — пожнешь поступок, посеешь поступок — пожнешь привычку, посеешь привычку — пожнешь характер, посеешь характер — пожнешь жизнь»._

Если пропустить промежуточные звенья этой цепочки, то мы получим: «Посеешь мысль... -> пожнешь жизнь». Отсюда можно сделать вывод, что от того, как и о чем человек думает, зависит вся его жизнь. И если он сможет изменить свои мысли – его жизнь тоже изменится.

Полезно задать вопрос: «А откуда у человека мысли? Почему он думает именно так?» Ответ прост: мысли исходят из ума. Однако Веды утверждают (_Бхагавад-гита_, 3.42), что выше ума, с его мыслями, чувствами и желаниями, стоит разум — вместилище мировоззрения человека. Именно сформированное мировоззрение человека и определяет образ мысли, в соответствии с которым работает его ум.

Таким образом, мы можем сказать **«Посеешь мировоззрение, … -> пожнешь жизнь»** . Мировоззрение играет ключевую роль в жизни человека и в зависимости от того, каково оно, человек будет по-разному смотреть на мир, совершать различные поступки и стремиться к разным видам наслаждений. В результате он будет испытывать различные виды страданий, которые приходят к нему как реакции материальной природы на его неправильные поступки. Поэтому очень важно понять, что различные страдания — это сигнал, напоминающий нам: что-то в своей жизни мы делаем неправильно, — нарушен какой-то закон, ибо наказывают только нарушителей.

== Но как разобраться во всем этом? Какие законы я нарушаю и как мне изменить свои взгляды на мир?

Человек может изменить свое мировоззрение двумя способами: либо прилагая сознательные усилия к этому, либо через опыт страданий и кризисов в жизни, приходящих как реакции на его ошибки. В связи с этим, мы можем видеть две категории людей, стремящихся к счастью: одни пытаются искоренить причину страданий внутри себя и осознанно стремятся к внутреннему изменению, а другие стремятся избавиться только от внешних причин страдания, не признавая своих недостатков. Рассмотрим, какая из этих позиций более разумна:

.2

[cols="2,4,4"]
|===
аспект |Ищущие причину внутри себя| Ищущие причину вне себя |
Отношение к своему мировоззрению |  Ясно понимают прямую связь между своим мировоззрением и качеством своей жизни и потому осознанно стремятся изменить мировоззрение.
| Смутно понимают, или вообще не отдают себе отчета в том, что события, происходящие с ними в жизни, напрямую связаны с их мировоззрением и даже не стремятся разобраться в этом.

|Получает знание|Через образование и позитивное общение.
|Через тяжелый опыт страданий, кризисов и разочарований.

| Смена мировоззрения происходит | Благодаря осознанному выбору (применению свободы воли) | Когда жизнь разрушает его (человек вынужден изменить свои взгляды, т.к. испытал крах).

| Тип веры | Вера осознанная, глубокая | Вера слепая (фанатичная или основанная на сантиментах).

| Стиль жизни | Активный, упреждающий | Пассивно реагирующий |

|===




Как видно из таблицы, есть 2 вида смены мировоззрения:

1. человек сам стремиться найти истину
2. он ждет, пока жизнь разрушит его неверные воззрения

Учитывая проведенное сравнение, не трудно заметить, что из этих двух вариантов, внутреннее изменение сознания с помощью образования и позитивного общения — метод гораздо более безболезненный и достойный человека. Если воспользоваться им, можно разрешить «главное жизненное противоречие».

**Что это за знание, которое способно так благотворно повлиять на мою жизнь и существует ли оно вообще? Кто является источником этого Абсолютного знания, и каким способом его можно получить?**** **