Urok 25                стр. 1 из 3

ВЕДИЧЕСКАЯ ФИЛОСОФИЯ (БАЗОВЫЙ КУРС)

Урок 25.

«СРАВНЕНИЕ ДУХОВНОГО И МАТЕРИАЛЬНОГО МИРОВ»

Каково отличие материального мира от духовного мира, и материальных
отношений от духовных?

Материальный мир является зеркальным отражением духовного мира. В нём
изначальные духовные взаимоотношения (расы) проявляются извращенно и
являются лишь бледным отражением этих истинных взаимоотношений. И, хотя
отражение может быть очень похожим на реальный объект, тем не менее, оно
лишь бледно напоминает о нём. Такое искажённое проявление любви называют
кама — «вожделение».

В Чайтанья-чаритамрите (Ади, 4.164-165) говорится о различии между
«любовью» материального мира (кама) и чистой любовью духовного мира
(према):

кама, према — донхакара вибхинна лакшана

лауха ара хема йаичхе сварупе вилакшана

атмендрийа-прити-ванчха таре бали ‘кама’

кришнендрийа-прити-иччха дхаре ‘према’ нама

«Вожделение и любовь также отличаются друг от друга, как железо и
золото. Желание услаждать собственные чувства именуется камой,
вожделением, а желание услаждать чувства Господа Кришны называют премой,
или чистой любовью».

Обусловленная душа в материальном мире получает возможность насладиться
материальными отношениями, которые называются пракрита-раса и являются
лишь бледным отражением бхакти-расы духовного мира:

Д У Х О В Н Ы Й   М И Р
^^^^^^^^^^^^^^^^^^^^^^^

мадхурья-раса

Д Е Г Р А Д А Ц И Я
+++++++++++++++++++

Д Е Г Р А Д А Ц И Я

В О З В Ы Ш Е Н И Е
+++++++++++++++++++

В О З В Ы Ш Е Н И Е
ватсалья-раса

сакхья-раса

дасья-раса

шанта-раса
~~~~~~~~~~

шанта-раса
лже-шанта-раса

лже-дасья-раса

лже-сакхья-раса

лже-ватсалья-раса

лже-мадхурья-раса

М А Т Е Р И А Л Ь Н Ы Й   М И Р
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Таким образом, материальный мир — это мир где отношения основаны на
вожделении, а духовный мир — это мир чистых, бескорыстных отношений,
основанных на любви. В этом заключается основное различие между ними.
Поскольку живое существо не может жить без расы, любовных
взаимоотношений, вкус которых очень сладок, оно ищет именно этих
отношений. Но проблема заключается в том, что, совершая роковую ошибку,
живое существо принимает каму за прему, которые отличаются друг от друга
также, как железо отличается от золота. Поэтому преданные Кришны
рассматривают эту привязанность к материальным наслаждениям как форму
страдания, ибо именно эта привязанность лишает человека решимости
посвятить себя преданному служению Кришне и обрести прему — истинную
безграничную любовь. Вот что об этом говорит Кришна в Бхагавад-Гите
2.44:

бхогайшварья-прасактанам

тайапахрита-четасам

вйавасайатмика буддхих

самадхау на видхйате

«Тем, кто слишком привязан к чувственным удовольствиям и материальному
богатству и чей ум из-за этого всё время пребывает в заблуждении, не
хватает решимости посвятить себя преданному служению Верховному
Господу».

Поэтому, разумный человек, хорошо понимая природу материальных
удовольствий, не ищет в них счастья (Бхагават-Гита 5.22):

йе хи самспарша-джа бхога

духкха-йонайа эва те

адй-антавантах каунтейа

на тешу рамате будхах

«Разумный человек сторонится удовольствий, рожденных от соприкосновения
материальных чувств с объектами восприятия, ибо такие удовольствия
являются источниками страданий. У всех материальных удовольствий, о сын
Кунти, есть начало и конец, поэтому мудрец никогда не тешится ими».

Итак, человек, лишенный знания об истинной природе бхакти-расы,
привязывается к материальным наслаждениям, пытаясь выжать из них как
можно больше удовольствия. Но какое бы наслаждение не получал человек в
материальном мире, оно, подобно капле воды, всё равно не сможет утолить
жажду его сердца. Шрила Прабхупада пишет:

«…В обусловленном состоянии люди, как правило, ищут утешения в обществе,
дружбе и любви. Эта их так называемая любовь — не более чем вожделение,
и всё же людей вполне устраивает такое ложное представление о любви.
Видьяпати, великий мудрец и поэт Митхилы, писал, что счастье, которое мы
находим в мирской дружбе, обществе и семейной жизни подобно капле воды,
тогда как сердца наши жаждут океана счастья. Он сравнивает сердце с
пустыней материального существования, и, чтобы оросить эту пустыню,
нужен целый океан удовольствий. Одна капля в пустыне ничего не стоит,
хотя это тоже вода. Точно также в материальном мире никого не могут
удовлетворить общество, дружба и любовь. Тот, кто желает ощутить в
сердце подлинное счастье, должен устремиться к лотосу стоп Говинды. В
этом стихе Рупа Госвами говорит, что если человек хочет наслаждаться
мирским общением, дружбой и любовью, ему не следует искать прибежища у
лотосоподобных стоп Говинды, иначе он позабудет о своих ничтожных мнимых
удовольствиях. Тот же, кого не радует так называемое счастье в
материальном мире, должен искренне захотеть найти прибежище у лотоса
стоп Говинды, который стоит на берегу Ямуны у Кеши-гхата, во Вриндаване
и вдохновляет всех гопи на любовное запредельное служение Ему»
(Чайтанья-чаритамрита, Ади 5.224, комм.).

Как ведет себя живое существо, охваченное камой — «вожделением», и как
ведет себя преданный Кришны, охваченный премой — чистой любовью к Нему?

Все обитатели духовного мира, движимые чистой любовью, вступают в
различные духовные взаимоотношения с Кришной и друг с другом с
единственной целью — доставить удовольствие Кришне. И это естественно,
поскольку тот, кто любит, делает все лишь ради удовольствия своего
возлюбленного. В духовном мире наслаждение Кришны находится в центре
всех взаимоотношений и поступков его обитателей. Поэтому духовный мир
является очень гармоничным и исполненным блаженства местом, никогда не
омрачаемым ссорами и конфликтами. В своём стремлении доставить
удовольствие Кришне, все преданные лишь дополняют друг друга, увеличивая
наслаждение Кришны. Так они становятся частью постоянно возрастающего
наслаждения Кришны.

 Но в материальном мире живое существо, охваченное вожделением, ставит
себя в центр и все поступки и взаимоотношения строит, исходя из этой
предпосылки, пытаясь расширить своё наслаждение. По этой причине
интересы живых существ постоянно пересекаются, что порождает вражду,
соперничество и войны. Результатом такого образа жизни являются
постоянно увеличивающиеся иллюзия и скорбь.

                      Духовный мир:                                    
                  Материальный мир:

Любовь и вражда это две крайности, которые никак не сочетаются друг с
другом. Невозможно говорить о наличии любви, если при этом у человека
остаётся чувство вражды и неприязни к окружающим его живым существам.
Поэтому уровень духовного развития человека можно оценить по этому
критерию — насколько он избавился от вражды и неприязни к другим.

Итак, до тех пор, пока находясь под влиянием ложного эго, человек будет
ставить в центр своё наслаждение, а не наслаждение Кришны, он будет
вынужден находиться в материальном мире, специально предназначенном для
того, чтобы удовлетворить его желание наслаждаться отдельно от Бога.
Однако если человек сделает Кришну центром наслаждения, посвятив себя
преданному служению Ему, тогда он избавится от материальных страданий и
возвысится до духовного мира.

[cols=",",]
|====================================================
|[multiblock cell omitted] |[multiblock cell omitted]
|Према (Я — слуга Кришны) |Кама (Я — наслаждающийся)
|[multiblock cell omitted] |[multiblock cell omitted]
|Духовный мир |Материальный мир
|Мир и гармония |Вражда и соперничество
|====================================================

Кришна в центре
---------------

Кришна в центре
«Я» в центре
------------

«Я» в центре
В Бхагавад-гите 5.29 Кришна говорит:

бхоктарам йаджна-тапасам

сарва-лока-махешварам

сухридам сарва-бхутанам

джнатва мам шантим риччхати

«Человек, полностью сознающий, что Я — единственный, кто наслаждается
всеми жертвоприношениями и плодами подвижничества, что Я — верховный
владыка всех планет и полубогов, а также друг и благожелатель всех живых
существ, избавляется от материальных страданий и обретает полное
умиротворение».

Этот стих есть формула мира. До тех пор пока человек не поставит Кришну
в центр своей жизни, он будет терпеть наказания от материальной природы,
приходящих в виде трёх видов страданий:

1.  Страдания от других живых существ
2.  Страдания от собственного тела  ума
3.  Страдания от стихийных бедствий

Все эти виды страданий являются реакцией на неправильные поступки
человека.

В третьей части этого семинара мы более подробно рассмотрим, что
означает поставить Кришну в центр всех своих взаимоотношений и как
реально можно осуществить это в своей жизни.

Означает ли, что для того, чтобы предаться Кришне, нужно разорвать все
свои взаимоотношения с миром?

Это одна из ошибок, которую мы можем сделать. В действительности
необходимо не разрывать отношения, а одухотворить их, развив своё
«сознание Кришны». В уроке №1 мы уже говорили о том, что причину
страданий нужно искать не в окружающем нас мире, и не в окружающих нас
людях, а в своём собственном сознании. Изменить своё сознание возможно
через общение со святыми преданными и систематическое духовное обучение.
Именно состояние сознания определяет круг нашего общения и нашу судьбу.
Поэтому, если Вы одухотворите свою жизнь, развив в себе сознание Кришны,
тогда Ваши отношения с окружающими Вас людьми также одухотворятся.

Подводя итог этого урока, мы можем заключить, что обусловленные души в
материальном мире стали жертвой роковой ошибки, приняв каму за прему.
Привязанность к чувственным услаждениям усиливает привязанность к телу,
которое является лишь грубым механизмом для исполнения желаний человека.
 В результате живое существо становится узником материального мира.

Почему живое существо оставляет любовь и гармонию духовного мира и
оказывается узником материального мира? Почему кто-то находится в
духовном мире, а кто-то в материальном? Кто определяет, где живому
существу находиться?
