Урок 15. КРИШНА — ОБЛАДАТЕЛЬ ВСЕХ ЭНЕРГИЙ

[.lead]
Какими же энергиями обладает Кришна?

Веды утверждают, что Кришна, являясь Абсолютом, обладает безграничными
энергиями. Одно из качеств Верховной Личности называется сатйа-санкалпа,
что означает следующее: любое Его желание или намерение всегда в
совершенстве выполняется Его разнообразными энергиями. Его желание — это
уже свершившийся факт.

Это подтверждается в «Шветашватара Упанишад» 6.8:

на тасйа карйам каранам ча видйате +
на тат-самаш чабнйадикаш ча дришйате +
парасйа шактир вивидхайва шруйате +
свабхавики джнана-бала-крийа ча

«Верховному Господу ничего не нужно делать Самому — всё выполняют Его
разнообразные энергии. На свете нет никого равного Ему или более
великого, чем Он».

Таким образом, Верховному Господу нет необходимости тяжело трудиться для
того, чтобы что-то происходило в духовном и материальном мироздании. Всё
приводится в движение безграничными энергиями Кришны, которые действуют
в соответствии с Его желанием и волей.

Его энергии бесчисленны, божественны, вечны и составляют всё сущее.
Энергии Кришны всегда находятся с Ним, Ему не нужно делать что-либо,
чтобы приобрести их. И по количеству, и по качественному составу Его
энергии бесконечны и постоянно расширяются. Поэтому их невозможно
описать полностью.

[.lead]
Если Его энергии безграничны, как же можно понять их?

Для более ясного понимания Веды подразделяют энергии Кришны на три
основные категории (Чайтанья Чаритамрита, Мадхья 20.111):

кришнера свабхавика тина-шакти-паринати

чит-шакти, джива-шакти, ара майа-шакти

«Господь Кришна обладает тремя энергетическими преобразованиями, которые
известны как:

1.  Антаранга-шакти Внутренняя энергия (духовная или
высшая энергия).
2.  Татастха-шакти Пограничная энергия (живые существа
или души).
3.  Бахиранга-шакти Внешняя энергия (материальная или
низшая энергия).

Духовный мир является проявлением внутренней энергии. Материальный мир —
проявление внешней энергии. Живые существа относятся к пограничной
энергии. Они вечные духовные частички, но, являясь очень маленькими
(ану) они не могут быть независимы и потому склонны принимать прибежище
либо духовного, либо материального миров.

В каждой из этих 3-х реальностей присутствуют другие три вида энергий, о
которых уже упоминалось ранее:

1.  Энергия вечности (сат, или сандхини).
2.  Энергия знания (чит, или самвит).
3.  Энергия блаженства (ананда, или хладини).

В результате воздействия энергий вечности, знания и блаженства на
внутреннюю, пограничную и внешнюю энергии, возникает все творение
Господа:

[cols=",,,",]
|====
|Энергия |Вечности (сандхини) |Знания (самвит) |Блаженства (хладини)

|Внутренняя |Духовный мир, Имена Бога, Его различные формы, качества и
игры Господа с Его спутниками, объекты и все, что необходимо для игр
Верховного Господа. |Весь спектр трансцендент-ных любовных
умонаст-роений (бхава), т.е. образов мысли. |Чистая духовная любовь,
приносящая величайшее наслаждение (према).

|Пограничная |Духовное существование живого существа, его вечные имя,
духовная форма, и качества. |Имперсональное знание  о Брахмане.
|Блаженство реализации Брахмана и положения в Нем.

|Внешняя |Материальная Вселенная, состоящая  из 14-ти планетных систем,
грубые и тонкие тела живых существ. Материальные чувства и материальные
цели, такие как достижение рая. Материальные имена, формы, качества, и
действия воплощенных существ |Обусловленное мышление живых существ,
надежды, беспокойства, воображе-ния и суждения. |Счастье, получаемое от
гру-бых материальных наслаж-дений живых существ, а также от утонченных
материальных наслаждений на высших планетах.
|====

Следует отметить, что для живого существа (дживы) материальные
наслаждения совершенно незначительны. Природа живого существа не
незначительна, однако недостаточна. Пока живое существо не соприкоснётся
с хладини-шакти во внутренней энергии, оно никогда не сможет ощутить
абсолютное, безграничное счастье. Однако достичь его невозможно без
милости Кришны или Его чистого преданного.

Что из себя представляет творение Господа?

Все творение Господа состоит из двух основных частей — духовного и
материального миров. «Одна четверть всех проявлений сандхини-шакти
Господа приходится на материальный мир, а три четверти на духовный…»
(Шримад-Бхагаватам 2.6.19, комм.). Поэтому материальный мир называют
эка-пада вибхути, а духовный три-пада вибхути (Чайтанья Чаритамрита,
Мадхья 21.57).

Материальный мир состоит из бесчисленного количества Вселенных, имеющих
яйцеобразную форму, каждая из которых покрыта семью оболочками. Поэтому
внутри Вселенной очень темно и, чтобы осветить её, в каждой Вселенной
есть лучезарная планета Солнце, которая светит отраженным светом
брахмаджьоти — духовного сияния, исходящего от тела Кришны. Все эти
Вселенные плавают в «причинном океане» (подробнее о причинном океане в
уроках №20-22), подобно пузырькам пены. Внутренний диаметр нашей
Вселенной составляет 6,5 миллиардов километров (Шримад-Бхагаватам
5.20.43). Внутри каждой Вселенной располагается 14 планетных систем.
Семь из них: Бхур, Бхувар, Свар, Махар, Джанас, Тапас и Сатья,
расположенные одна над другой, относятся к высшим планетным системам.
Семь низших планетных систем (в нисходящем порядке) называются Атала,
Витала, Сутала, Талатала, Махатала, Расатала и Патала.

Низшие планетные системы населяют змеи и змееподобные существа — Наги, а
также материалисты и демоны. В материальном отношении эти планеты могут
находиться даже на более высоком уровне развития материальной
цивилизации, чем Земля, но цель этого развития одна — удовлетворение
чувств.

Планета Земля, называемая Бхур-локой, находится прямо посередине
Вселенной. Ее населяют человеческие и другие смертные живые существа.
Земля играет во Вселенной особую роль, ибо, попав на неё, живое существо
в человеческом теле создаёт последствия (карму) своих действий и таким
образом определяет своё будущее назначение. В зависимости от того, какие
реакции накопил человек, он попадает на ту или другую планету, где и
отрабатывает эти реакции. Земля — это также место,  предназначенное для
духовной практики, поскольку оно свободно от излишней роскоши для
удовлетворения чувств и излишних страданий, которые отвлекают ум живого
существа.

Высшие уровни планетных систем населяют сиддхи, чараны, видьядхары,
кимпуруши, духи, привидения, полубоги; еще выше — мудрецы, аскеты,
давшие обет безбрачия. На высшей планете материального мира, Сатьялоке,
представляющей собой лотос, несёт своё служение Господь Брахма (первое
живое существо во вселенной) со своими спутниками. На этих планетах есть
неограниченные возможности и для преданного служения, и для тонкого
удовлетворения чувств. Все обитатели этих планет преданы Господу, хотя и
в разной степени.

Помимо этих планетных систем, в нижней части Вселенной находится особая
область, состоящая из 28 адских планет и называемая Ямапури. Сюда
попадают люди, совершающие чрезвычайно греховную деятельность. Эта
особая область Вселенной отделена огненной рекой Вайтарани.

Материальный мир отделен от духовного мира духовной рекой, называемой
Вираджа. За рекой Вираджей находится «Причинный океан», а за ним
начинается духовное небо, залитое ослепительным сиянием Брахмана — лучей
исходящих от трансцендентного тела Кришны. В этом сиянии плавают
бесчисленные духовные планеты, именуемые Вайкунтхами. Среди всех
духовных планет, одна является наивысшей и называется Голока или
Кришналока. Эта Планета разделена на три части, называемые Дварака,
Матхура и Вриндаван.

Как мы уже упоминали в предыдущих уроках, во всех этих духовных обителях
Господь пребывает в одной из Своих трансцендентных форм. Но в Своей
изначальной форме, украшенной всеми 64 качествами Верховной Божественной
Личности, Кришна всегда остается во Вриндаване — высшей сфере Творения
Господа.

Ниже мы приводим схему, которая дает некоторое представление о
безграничном Творении Господа:

АНТАРАНГА — ШАКТИ
+++++++++++++++++

АНТАРАНГА — ШАКТИ
(Духовный мир — ¾ творения)

Вриндаван
---------

Вриндаван
Айодхйа
-------

Айодхйа
Вайкунтха
---------

Вайкунтха
Дварака
-------

Дварака
Матхура
-------

Матхура

[.lead]
Что собой представляют внешняя, внутренняя и пограничная энергии
Господа?
