Urok 18                стр. 1 из 3

ВЕДИЧЕСКАЯ ФИЛОСОФИЯ (БАЗОВЫЙ КУРС)

Урок 18

«ВОЗВЫШЕНИЕ НАД ГУНАМИ СТРАСТИ И НЕВЕЖЕСТВА»

Как же преодолеть влияние гун материальной природы?

Ответ на этот вопрос дается в Шримад-Бхагаватам 11.13.1:

«Три гуны, а именно: благость, страсть и невежество - связаны с
материальным разумом, а не с духовной душой. Развивая в себе качества,
присущие материальной благости (саттва-гуне) можно преодолеть влияние
гун страсти и невежества, а, развивая в себе качества, присущие
трансцендентной благости (вишуддха-саттве), можно избавиться даже от
влияния материальной благости».

В процитированном стихе есть три важных момента, описывающих процесс
освобождения от влияния гун, два из которых мы обсудим в этом уроке, а
один в следующем.

1.  Чтобы выйти из-под влияния гун, необходимо очистить свой разум,
приобретая трансцендентное знание.

Это основополагающий принцип. В стихе подчеркивается то, что «три гуны
связаны с материальным разумом». Разум играет очень важную роль в жизни
человека, ибо решимость действовать тем или иным образом приходит из
него. Он является вместилищем веры человека, и в зависимости от
сформированной веры или мировоззрения он будет жить и действовать под
влиянием соответствующего сочетания гун и достигать соответствующего
результата в жизни. Вера человека может меняться — это зависит от того,
с кем он общается. В известной пословице говорится: «С кем поведешься,
от того и наберёшься». Чтобы обрести истинную веру, Веды рекомендуют нам
общаться со святыми людьми, обладающими ею (Шримад-Бхагаватам 3.25.24).
Такое общение пробуждает решимость двигаться по пути к освобождению от
гун и достичь высшего состояния бытия, не подвластного гунам
материальной природы. Поэтому, общаясь со святыми и систематически
обучаясь духовной науке, каждый получает реальную возможность изменить
свою жизнь и её результат.

1.  Освобождение от гун происходит постепенно. Сначала необходимо
развить в себе качества, присущие материальной гуне благости
(саттва-гуне), и так преодолеть влияние гун страсти и невежества.

Чтобы обрести чистый разум, необходимо также ограничить свое общение с
низшими гунами (страстью и невежеством) и общаться только с гуной
благости, ибо, находясь под влиянием низших гун, человек неминуемо будет
преследовать корыстные цели в своих поступках, а это будет осквернять
его сознание и приведёт к деградации. Но в гуне благости человек
счастлив, и потому его поступки становятся бескорыстными. Такой человек
быстро очищается и обретает способность правильно выбирать то, что
благоприятно для его духовного здоровья. Чтобы понять, как развить в
себе влияние гуны благости, обратимся к наставлениям Кришны в
Бхагавад-гите и Шримад Бхагаватам.

1.  Закон влияния гун описывается в Бхагавад-гите 14.10:

«Иногда, о сын Бхараты, в человеке начинает преобладать гуна благости,
одолевая страсть и невежество. Иногда гуна страсти побеждает невежество
и благость, а иногда берет верх гуна невежества. Так между гунами
материальной природы идет непрерывная борьба за превосходство».

Таким образом, проявлениями гун можно управлять, так как с помощью одной
гуны можно победить другие. Если человек сосредотачивает свое сознание
на одной из гун, её влияние сразу же увеличивается за счет уменьшения
влияния двух других. Поэтому, если человек сосредоточится на гуне
благости, она вытеснит из его жизни влияние гун невежества и страсти.

Благость
--------

Благость
Невежество
----------

Невежество
Страсть
-------

Страсть
1.  В Бхагавад-гите Кришна описывает различные сферы жизни человека.

В зависимости от того, в какой гуне протекает жизнь, человек будет
достигать соответствующего ей результата. Ниже приводится таблица с
описанием этих сфер жизни:

«Сферы жизни человека в различных гунах материальной природы»

[cols=",,",]
|=======================================================================
|ВЛИЯНИЯ |САТТВА (благость) |РАДЖАС (страсть) |ТАМАС (невежество)

|(БГ17.8-10) |Пища, которая увеличивает продолжительность жизни, очищает
сознание, прибавляет сил, здоровья, приносит счастье и удовлетворение.
Сочная, маслянистая, здоровая и приятная сердцу пища. |Пища чрезмерно
горькая, кислая, соленая, пряная, острая, сухая и очень горячая.
Является источником горя, страданий и болезней. |Пища, приготовленная
более чем за три часа до еды, безвкусная, несвежая, протухшая, нечистая
и состоящая из чужих объедков.

|[multiblock cell omitted] |Сделанные из чувства долга, а не в расчете
на вознаграждение, которые делаются в надлежащее время, в надлежащем
месте достойным людям. |Совершаются в расчете на вознаграждение, с
желанием в будущем насладиться их плодами или же неохотно. |Совершаются
в нечистом месте, в неурочное время, по отношению к недостойному
человеку и без должного внимания и уважения.

|(БГ 18.7-9) |Выполняет предписанные обязанности из чувства долга, без
привязанности к плодам. |Отказывается выполнять свой долг из-за того,
что это слишком обременительно или из страха. |Перестает выполнять свои
обязанности, введенный в заблуждение.

|(БГ18.20-22) |Знание, позволяющее человеку, несмотря на многообразие
видов и форм живых существ, видеть их единую духовную форму. |Знание о
том, что в разных телах находятся разные по природе живые существа.
|Знание, привязывающее человека к одному виду деятельности как к
единственно важному, не дающее представление об истине и отличающееся
узостью и скупостью.

|[multiblock cell omitted] |Упорядоченная деятельность, в основе которой
нет привязанности, любви и ненависти или желания насладиться ее плодами.
|Деятельность, требующая огромных усилий, направленная на исполнение
собственных желаний и продиктованная ложным эго. |Деятельность,
вызванная заблужде-ниями, противоречащая указаниям Священных писаний,
без учета ее порабощающих последствий; или деятельность с применением
наси-лия, которая причиняет страдания другим живым существам.

|(БГ18.26-28) |Тот, кто исполняет свой долг, не обращая внимания на гуны
материальной природы и ложное эго, кто действует с великой решимостью и
энтузиазмом и кто остается невозмутимым в успехе и неудаче. |Привязан к
деятельности и ее результатам, движим желанием насладиться плодами
своего труда, жаден, злобен, нечист, подвержен радостям и печалям.
|Постоянно поглощенный деятель-ностью, противоречащей указаниям
священных писаний, материалистичный и упрямый, обманывающий и постоянно
оскорбляющий других, ленивый, всегда угрюмый, откладывающий все на
потом.

|[multiblock cell omitted] |Разум, способный определить, что следует и
чего не следует делать, чего следует и чего не следует бояться, что
порабощает и что ведет к освобождению. |Разум, не способный отличить
религию от безбожия, действие дозволенное от действия запрещенного.
|Разум, принимающий безбожие за религию, а религию за безбожие,
запутавшийся, погруженный во тьму и постоянно сбивающий человека с
истинного пути.

|(БГ18.33-35) |Непоколебима и делает человека целеустремленным в
занятиях йогой, позволяя ему овладеть своим умом, потоками жизненного
воздуха и чувствами. |Побуждает человека стремиться к плодам религии,
материального благополучия и чувственных наслаждений. |Лишена
рассудительности и не может избавить человека от сновидений, страха,
скорби, подавленности и иллюзии.

|(БГ18.37-39) |Вначале кажется ядом, а в конце становится подобным
нектару; пробуждает человека к самосознанию. |Возникающее от
соприкосновения чувств с их объектами; вначале кажется  нектаром, а в
конце становится подобно яду. |Ослепляет человека, лишая его возможности
постичь природу души, обманчивое вначале и в конце, порожденное сном,
ленью и иллюзией.

|[multiblock cell omitted] |Попадает на высшие, чистые планеты великих
мудрецов. |Рождается на планете типа Земля и занимается корыстной
деятельностью. |Рождается среди животных или на низших (адских)
планетах.
|=======================================================================

СФЕРА
-----

СФЕРА
ВЛИЯНИЯ
