== Урок 9. БХАГАВАН — ВЕРХОВНАЯ БОЖЕСТВЕННАЯ ЛИЧНОСТЬ — ЯВЛЯЕТСЯ ВЫСШИМ ПРОЯВЛЕНИЕМ АБСОЛЮТНОЙ ИСТИНЫ

[.lead]
Кто же этот изначальный Верховный Господь, обладающий самым полным,
совершенным знанием? Является ли Он личностью или же Он безличен?

В соответствии с Ведами, Бог может проявляться в трёх аспектах, о
которых говорится в Шримад-Бхагаватам (1.2.11):

[quote, Шримад-Бхагаватам, 1.2.11]
--
ваданти тат таттва-видас +
таттвам йадж джнанам адвайам +
брахмети параматмети +
бхагаван ити шабдйате +

«Абсолютную Истину постигают в трёх аспектах, которые не отличны друг от
друга. Их называют Брахманом, Параматмой и Бхагаваном».
--

Итак, между этими тремя аспектами Абсолютной Истины нет разницы в
качественном отношении, ибо все они являются духовными проявлениями
единого Бога. В этом заключается их единство. Однако существует и
некоторая духовная разница, иначе не было бы никакой необходимости в
существовании этих трёх категорий. По сути дела, в этих трёх аспектах
единый Господь раскрывает Себя в разной степени. Давайте же
проанализируем, на какой из этих трёх ступеней истинная сущность Господа
раскрывается полнее всего:

1.  Брахман — это безличное проявление Бога, аспект Его вечного бытия,
на который указывает санскритское слово сат — «вечность». Постижение
Брахмана является начальной ступенью постижения Абсолюта. Те, кто постиг
Брахман, достигают состояния освобождения от материального сознания. К
этому уровню совершенства стремятся люди, занятые гьяна-йогой, суть
практики которой состоит в размышлении над природой Абсолютного путем
отрицания временных объектов этого материального мира. Такие люди
пытаются понять, чем Абсолют не является: Он не то и не это, Он не ходит
и не лежит, Его нельзя познать и нельзя почувствовать и т.п. Так,
размышляя над тем, что является духом, а что материей, такие люди
постепенно начинают различать проявления духа и познают Брахман —
ослепительное сияние, исходящее от тела Бога, по-другому называемое
брахмаджьоти. И хотя они достигают состояния осознания своего вечного
существования, такое совершенство — лишь первая ступень постижения
Абсолютной Истины.

2.  Параматма (парама — «Высшая», и атма — «Душа») — это локализованное
проявление Бога, присутствующее в каждом атоме творения и в сердце
каждого живого существа. Как Параматма Господь пронизывает Собой все
Творение и поддерживает его. При этом Сам лично Он не вмешивается в дела
этого материального мира. Он просто наблюдает за желаниями живых существ
и дозволяет их удовлетворить, если позволяет их карма (результаты
деятельности). Если безличный Брахман по определению непознаваем, то
трансцендентную форму Сверхдуши уже могут созерцать достигшие
совершенства йоги-мистики, практикующие аштанга-йогу (восьмиступенную
мистическую йогу). Достигнув этого уровня осознания, человек познаёт
аспекты вечности, сат, и знания, чит Господа. Это вторая ступень
постижения Абсолютной Истины.

3.  Бхагаван — полное проявление Абсолютной Истины, последний шаг
постижения запредельного. В этом аспекте Абсолютная Истина является
источником всего сущего. Если Брахман лишь просто существует где-то за
пределами материального творения, а Параматма пассивно поддерживает всё
в материальном мире, то Бхагаван, будучи причиной всех причин и
источником всего сущего, играет активную творческую роль. Такая
индивидуальная творческая активность личностна по своей природе и
исполнена блаженства — ананда. Поэтому только тот, кто постиг полное
проявление Бога как Бхагавана, достигает состояния безграничного
счастья, осознав все три аспекта Абсолюта: сат — «вечность», чит —
«знание» и ананда — «блаженство». Практика, позволяющая постичь
Верховную Личность Бога, называется бхакти-йогой — чистым преданным
служением Ему.

Итак, мы можем видеть, что больше всего Божественных аспектов проявлено
на ступени реализации Бхагавана, а именно — сат, чит и ананда (вечность,
знание и блаженство). Поэтому, Бхагаван есть высшее проявление Бога.
Реализация безличного Брахмана и локализованной Параматмы — является
лишь частичным осознанием Бога и позволяет воспринять Его лишь
ограниченно. Примечательно, что постижение высшего аспекта Абсолюта
включает в себя и реализацию низшего. Поэтому, постижение Параматмы
включает реализацию Брахмана, а постижение Верховной Личности Бога,
Бхагавана, включает реализацию и Брахмана и Параматмы. Другими словами,
тому, кто постиг Бога в Его личностном аспекте, по Его милости
открывается всё знание. Господь подтверждает это в Бхагавад-гите
(15.19):

[quote, Бхагавад-гита, 15.19]
--
йо мам эвам асаммудхо +
джанати пурушоттамам +
са сарва-вид бхаджати мам +
сарва-бхавена бхарата +

«Всякий, знающий Меня как Верховную Божественную Личность, и не
сомневающийся в этом, знает всё, и потому полностью отдаёт себя
преданному служению Мне, о сын Бхараты».
--

Поскольку именно практика чистого преданного служения, или бхакти-йога,
позволяет достичь совершенства реализации Бхагавана, такая практика
является самой совершенной деятельностью живого существа.

[.lead]
Что происходит с человеком, который достиг лишь частичной реализации
Абсолюта — реализации Брахмана или Параматмы? Удовлетворён ли он
достигнутым совершенством и заканчиваются ли на этом его духовные
устремления?

=== Реализация безличного Брахмана.

Человек, постигший Брахман, обретает блаженство от осознания того, что
его природа едина с природой Брахмана, т.е. того, что он и Брахман
вечны. Это блаженство описывается словом брахмананда, происходящим от
слов брахма (Брахман) и ананда (блаженство). Обретя его, человек уже не
воспринимает окружающее как нечто существенное. Все стремления и
желания, понятия и убеждения вытесняются из его сознания. Он перестает
что-либо говорить, что-либо делать, и даже мышление его, помимо
осознания своей вечности, прекращается. Он не видит никакой разницы
между собой и другими живыми существами. Так, находясь на уровне
осознания Брахмана, человек обретает истинное знание об окружающем его
материальном мире и естественную отрешённость, порожденную таким
знанием. Природа недвойственного Брахмана полностью проявляется в его
сознании.

Такой человек, прекращающий свою деятельность (карму) в результате
самоосознания, черпает радость в собственном сердце (сознании). Тем не
менее, у него появляется очень тонкое, духовное чувство незавершённости.
Оно вызвано тем, что душа активна по своей природе и не может
бездействовать. Это чувство может явиться причиной последующих действий
двух видов:

1.  Благотворительность и желание нести послание истины другим людям.

1.  Поиск причины неудовлетворённости в себе.

Если человек принимает первое, то, действуя в материальном мире, пусть
даже с такими благородными целями как благотворительность и очищение
общества, он начинает обуславливаться материальной энергией, что
приводит его к постепенной деградации.

Второе вводит человека в состояние йогического транса, в котором
постигается Высшая Душа — Параматма. Так человек может прийти к
реализации более высокого аспекта Бога.

=== Реализация Параматмы (Сверхдуши).

В отличии от Брахмана, со Сверхдушой (Параматмой) могут устанавливаться
взаимоотношения. На этом уровне человек видит во всем присутствие
Сверхдуши. Отличие его осознания от предыдущего уровня состоит в том,
что теперь постигается Абсолютная форма. Параматма является кульминацией
всего мистицизма, т.к. все мистические совершенства в этом мире берут
свое начало в Ней. Человек черпает в созерцании образа Сверхдуши
безграничное блаженство. Погружаясь в такое созерцание, он входит в
единение со Сверхдушой, что позволяет ему проявлять, до какой-то
степени, мистические способности (сиддхи), присущие Ей.

И хотя человек, постигший Сверхдушу в процессе йогической практики,
удовлетворён в себе, тем не менее, в глубине сознания, как и в первом
случае, приходит духовное чувство незавершённости. Это чувство побуждает
йога к последующим действиям 2 видов:

1.  Использование обретенных мистических сил для удовлетворения
собственных желаний.

1.  Стремление к дальнейшему совершенству.

Если человек принимает первое, то, поражая обычных людей своими
мистическими способностями, он привязывается к славе и чувству
превосходства над другими. Это быстро оскверняет его разум, и он
объявляет себя богом. Так он деградирует вместе со своими
последователями, поймавшимися на приманку его фокусов.

Если же йог-мистик, преодолевает соблазн наслаждаться мистическими
способностями, и стремится постичь Истину, оставив все желания,
порожденные предыдущей деятельностью, то к нему приходит понимание,
выраженное в Шримад Бхагаватам 2.2.6:

«Человек должен служить Сверхдуше, пребывающей в его сердце. Она —
Всемогущая Божественная Личность, вечная и безграничная, поэтому Она
является высшей целью жизни, и, поклоняясь Ей, можно устранить причину
обусловленности своего существования».

Так, постепенно, медитация йога на Сверхдушу, превращается в преданное
служение, приводящее его к осознанию третьего аспекта Абсолютной Истины
— Бхагавана.

=== Осознание Бхагавана — Верховной Божественной Личности.

Благодаря преданному служению, йогу в сердце является изначальная
Божественная Личность — Бхагаван, источник безграничного блаженства,
которое в Ведах описывается словом «ананда». Так, соприкасаясь с
источником ананды, Верховной Божественной Личностью, через процесс
чистого преданного служения, живое существо, приобщившись к этому
блаженству, погружается в состояние неописуемого счастья.

Подводя итог урока, следует отметить, что до тех пор, пока человек,
стремящийся к совершенству, не достигнет реализации Бхагавана, он будет
ощущать незавершенность и продолжать поиск счастья (ананды). Поэтому
чистое преданное служение Верховной Божественной Личности, Бхагавану,
является высшей формой деятельности, приносящее живому существу полное
удовлетворение и счастье.

Это подтверждается в Шримад-Бхагаватам (1.2.6):

[quote, Шримад-Бхагаватам, 1.2.6]
--
са ваи пумсам паро дхармо +
йато бхактир адхокшадже +
ахаитукй апратихата +
йайатма супрасидати +

«Высшим делом для всех людей является такое занятие, с помощью которого
они могут прийти к любовному преданному служению запредельному Господу.
Чтобы полностью удовлетворить душу, такое преданное служение должно быть
бескорыстным и непрерывным».
--

[.lead]
Что означает санскритское слово «Бхагаван» и какое имя лучше всего
описывает Его? Почему существует много имён Бога?
