== Урок 13. СЛАДОСТЬ И МОГУЩЕСТВО ХАРЕ-КРИШНА-МАХА-МАНТРЫ

[.lead]
У Бога есть много различных имен. Если человек будет повторять другие
имена Бога, то какого результата он при этом достигнет?

Повторение любых имен Бога очень благоприятно, ибо оно очищает и
возвышает человека. Однако, благо от повторения разных имен может быть
разным.

Великий святой, Бхактивинода Тхакур, объясняет, что существует три типа
имен Бога:

1.  Гауна-нама — «второстепенные имена». Эти имена Господа связаны с Его
материальной энергией, создающей материальные вселенные. Это такие имена
как Сришти-карта — «Творец вселенной», Джагат-пати — «Управитель
вселенной», Брахман, Параматма, Ишвара — «Господин». Такие имена
описывают Бога с точки зрения обусловленных в материи душ, говорят о
том, как Он взаимодействует с ними. Такие имена Бога обычно повторяют
люди, которые хотят получить от Бога какие-то материальные блага, и
люди, стремящиеся освободиться из материального мира. Однако преданные
Бога не повторяют такие Имена. Повторение второстепенных имен Бога дает
благочестие, материальное возвышение и спасение.

1.  Мукхья-нама — «главные имена». Это Святые имена Господа, описывающие
Его надмирные игры. Повторение этих Имен, связанных с играми Кришны,
дает человеку кришна-прему (высшее проявление любви к Богу) и возвышает
его до Вриндавана — высшей обители в духовном мире. Это такие имена как
Говинда, Гопал, Рама, Шри Нанда-нандана, Радха-натха, Хари,
Яшомати-прана-дхана, Мадана-мохана, Шьямасундара, Мадхава, Гопинатха,
Враджагопал.

1.  Мадхурья-нама — «сладостные имена».

В своей книге «Кришна-самхита» Бхактивинода Тхакур пишет:

[quote, «Кришна-самхита», Бхактивинода Тхакур]
«…Маха-мантра состоит из самых сладостных имен Бога. Все виды
взаимоотношений находятся в харе-кришна-маха-мантре. Эти имена не
затенены ни величием (айшварья) Господа, ни стремлением к освобождению
(мукти). Эта маха-мантра раскрывается только тем душам, которые связаны
с Господом узами любви. Имена «Харе», «Кришна» и «Рама» особенно дороги
тем, кто стоит на пути мадхурья-расы (высочайший вид взаимоотношений с
Кришной, который в высшей степени наполнен сладостью чувств). Постоянно
повторяя эти Имена и медитируя на них, человек совершает наилучшее
служение Верховному Господу».


Итак, повторение харе-кришна-маха-мантры (маха — «великая песнь», манас
— «ум», трайа — «очищение») является самым могущественным методом
пробуждения дремлющей в нас любви к Богу.

1.  В Брихан-нарадия-пуране (3.8.126) подчеркивается:

харер нама харер нама харер намаива кевалам +
калау насти эва насти эва насти эва гатир анйатха

«В этот век Кали (нынешний период существования вселенной) нет другого
пути, нет другого пути, нет другого пути для достижения самоосознания,
кроме повторения Святого имени, повторения Святого имени, повторения
Святого имени Господа Хари».

1. В «Калисантарана Упанишад» говорится:

харе кришна харе кришна кришна кришна харе харе +
харе рама харе рама рама рама харе харе +
ити содашакам намнам кали-калмаша-нашанам +
натах паратаропайах сарва-ведешу дришьяте

«Шестнадцать святых имен в маха-мантре — харе кришна харе кришна
кришна кришна харе харе, харе рама харе рама рама рама харе харе —
разрушают неблагоприятное влияние века Кали. Таково заключение всех
Вед».

1.  В «Агни-Пуране» утверждается:

харе кришна харе кришна кришна кришна харе харе

ратанти халайа вапи те критартха на самшайах

«Харе кришна харе кришна кришна кришна харе харе: Кто бы ни повторял эту
маха-мантру, пусть даже неосознанно, достигнет высшей цели жизни. В этом
нет никаких сомнений».

Повторение Святых имен способно очень быстро очистить сердце человека,
если он будет повторять Их, избегая десяти оскорблений. Список этих
оскорблений таков:

1.  Поносить преданных, посвятивших свою жизнь распространению святого
имени.
2.  Считать имена таких полубогов, как Господь Шива и Господь Брахма,
обладающими тем же могуществом, что и имя Господа Кришны, или
независимыми от Него.
3.  Не повиноваться указаниям духовного учителя и считать его обычным
человеком.
4.  Поносить Ведическую литературу или литературу, согласующуюся с
ведическими представлениями.
5.  Считать мощь повторения «Харе Кришна» плодом воображения.
6.  Давать собственные толкования Святому имени Господа.
7.  Совершать греховные действия в расчете на очистительную силу Святого
имени Господа.
8.  Считать повторение «Харе Кришна» одной из форм благоприятной
обрядовой деятельности, рекомендуемой в Ведах в разделе «Карма-канда».
9.  Объяснять славу Святого имени неверующему.
10. Не иметь полной веры в повторение Святого имени Господа и сохранять
материальные привязанности, даже получив и поняв множество наставлений
на эту тему.

Невнимательность при повторении маха-мантры является корнем, из которого
вырастают все вышеперечисленные оскорбления. Каждый, кто повторяет
харе-кришна-маха-мантру, избегая этих десяти оскорблений, непременно
разовьет чистую любовь к Богу и в конце жизни вернется в Его обитель.

[.lead]
Что является причиной невнимательности и как её можно преодолеть?

Причиной невнимательности является глубоко укоренившаяся в человеке
привычка сосредотачиваться на самом себе или на том, что ему
принадлежит. Эта тенденция — результат эгоистического сознания, в основе
которого лежит гордость — причина всех бед человека. Именно гордыня в
сердцах людей порождает конфликты и войны, происходящие в материальном
мире и приводящие к неизбежным страданиям, поскольку «гордость приходит
перед падением», а падение всегда сопровождается скорбью и страданиями.
Гордость — это попытка возвеличить себя до положения Бога. Избавиться от
этого негативного качества человек сможет, если осознает верховное
положение Кришны и свою незначительность и подчиненность. Знания,
которые Вы получаете в этой части семинара, помогут Вам сделать это.
Обучение важно сочетать с повторением и пением Харе Кришна маха-мантры.
Необходимо набраться терпения, ибо процесс духовного осознания и
очищения потребует длительного времени. Если прилагать усилия к тому,
чтобы быть внимательным во время повторения маха-мантры и терпеливо
продолжать процесс, то постепенно способность концентрироваться на
святом имени будет увеличиваться. И даже небольшой шаг на этом пути
приносит радость.

Итак, истинный путь к счастью — это путь избавления от гордости и
развития подлинного смирения, которое является истинным украшением души.
Вышеописанные методы (получение истинного знания и повторение Святого
имени) — это наилучшие способы достижения счастья. Сам Кришна, приходя в
Своём самом милостивом воплощении — в образе Шри Чайтаньи, учит именно
этому и говорит:

[quote, Шри Шри Шикшаштака текст 3, Шри Чайтанья Махапрабху]
--
тринад апи суничена тарор апи сахишнуна +
аманина манадена киртанийах сада харих +
--

«Святые имена Господа следует повторять в смиренном состоянии ума,
считая себя ниже соломы, валяющейся на улице. Нужно стать терпеливее
дерева, полностью освободившись от чувства ложного престижа, и всегда
быть готовым оказать почтение другим. Только в таком состоянии можно
повторять Святое имя Господа постоянно».

[.lead]
Что это за воплощение Кришны — Шри Чайтанья, и почему Его называют Самым
милостивым?
