== Урок 10. КРИШНА — ВЕРХОВНАЯ БОЖЕСТВЕННАЯ ЛИЧНОСТЬ, ОН — ИСТОЧНИК ВСЕХ ВОПЛОЩЕНИЙ

[.lead]
Что означает санскритское слово «Бхагаван»?

В Вишну-Пуране великий мудрец и знаток Вед Парашара Муни
объясняет значение этого слова следующим образом:
[quote, Вишну пурана, 6.5.74]
--
айшварйасйа самаграсйа +
вирйасйа йашасах шрийах +
гьяна-вайрагйайош чайва +
саннам бхагам итигана +

«Того, Кто в полной мере обладает следующими шестью достояниями:
богатством, силой, славой, красотой, знанием и отрешённостью, называют
Бхагаваном».
--

На свете много людей, которые очень богаты, очень могущественны, очень
красивы, очень знамениты, обладают огромным знанием или способны к
высокой степени самоотречения. Однако никто из них не может претендовать
на то, что он обладает всеми богатствами, всей силой и прочими
качествами в полном объёме. Право говорить так о Себе имеет только
Верховный Господь, ибо на свете нет никого равного Ему или более
великого, чем Он.

[.lead]
Каким именем называть Бхагавана — Верховную Личность?

Перечисленные выше шесть достояний Бхагавана, Верховной Божествоенной
Личности, привлекают всех. Поэтому лучшее имя, которое можно дать
Бхагавану — это «Всепривлекающий», или на санскрите — Кришна. Итак,
Верховная Божественная Личность, Бхагаван — Кришна, Всепривлекающий.
Веды недвусмысленно говорят об этом, и ниже мы приводим лишь некоторые
из этих утверждений:

1.  В Брахма-самхите Господь Брахма, первое живое существо во
Вселенной, утверждает:

[quote, Брахма-самхите, 5.1]
--
ишварах парамах кришнах +
сач-чид-ананда-виграхах +
анадир адир говиндах +
сарва-карана-каранам +

«Кришна превосходит всех, ибо никто не может затмить Его. Он — Высшая
Личность, а Его вечное тело исполнено блаженства и знания. Он —
предвечный Господь Говинда, причина всех причин».
--

1.  В Шримад-Бхагаватам перечислено много воплощений Верховной
Божественной Личности. Однако Кришна назван в нём Изначальной Личностью,
Бхагаваном, источником всего множества воплощений:

[quote, Шримад-Бхагаватам, 1.3.28]
--
эте чамша-калах пумсах +
кришнас ту бхагаван свайам +
индрари-вйакулам локам +
мридайанти йуге йуге +

«Все перечисленные здесь воплощения Бога — это либо полные проявления,
либо части полных проявлений Верховного Господа, но Кришна — это Сам
Верховный Господь, Божественная Личность».
--

1.  В Бхагавад-Гите Сам Кришна утверждает, что нет истины выше,
чем Он:

[quote, Бхагавад-Гите, 7.7]
--
маттах паратарам нанйат +
кинчид асти дхананджайа +
майи сарвам идам протам +
сутре мани-гана ива +

«О завоеватель богатств, нет истины выше Меня. Все сущее покоится на
Мне, подобно жемчужинам, нанизанным на нить».
--

Таким образом, во всей Ведической литературе в различных местах, прямо
или косвенно, в комментариях или объяснениях, намёками или выводами,
именно Шри Кришна, а не кто-либо ещё, описывается как Верховный. Он
является источником как Параматмы, так и Брахмана.

В Чайтанья-чаритамрите утверждается:

[quote, Чайтанья-чаритамрите, Адилила 2.106]
--
свайам бхагаван кришна, кришна сарвашрайя +

парама ишвара кришна сарва шастре кайа +

«Шри Кришна, Божественная Личность — изначальный Верховный Господь,
причина всех экспансий (воплощений Бога). Все богооткровенные Писания
признают Шри Кришну Верховным Господом».
--

[.lead]
Люди называют Бога различными именами. Означает ли это, что есть много
Богов?

Конечно же Бог один. Если бы это было не так, то слово «Всевышний»
утратило бы своё смысловое значение. И хотя Верховный Господь один, у
Него есть множество имён, связанных с Его отдельными качествами или
особыми деяниями и взаимоотношениями. Чтобы явить эти особые деяния и
качества, Господь проявляет Себя в разных воплощениях (экспансиях),
которых в связи с этим называют разными именами. Поэтому, хотя Господь
един, у Него, тем не менее, бесконечное множество имён, которые
невозможно даже сосчитать, как невозможно сосчитать волны в океане.

[.lead]
Какие бывают воплощения Бога?

Являясь Верховной Личностью, Кришна может проявлять Себя одновременно во
множестве форм в разных местах, причем все эти формы могут одновременно
выполнять различные деяния. Такие формы Господа называют экспансиями.
«Экспансия» буквально означает «расширение, выход за первоначальные
пределы». В нашем случае, поскольку Господь беспределен, это будет
означать «То, что исходит от Кришны». Некоторые из таких экспансий
обладают всеми достояниями Верховной Божественной Личности. Такие
всемогущие формы Господа называются вишну-таттвами, то есть относятся к
той же категории Абсолютной Истины, что и Сам Кришна. Вместе с тем,
среди всех вишну-таттв Кришна занимает уникальное положение. В
Брахма-самхите вишну-таттвы сравниваются с горящими свечами. Хотя нет
разницы между пламенем этих свечей, тем не менее, одна из них отличается
тем, что с её помощью зажгли все остальные. Господь Кришна является
источником всех остальных «свечей».

Перечислим основные вишну-таттвы: Из Кришны исходит Господь Баларама. Из
Баларамы появляется первая четверичная экспансия (1-я чатур-вьюха) —
Васудева, Санкаршана, Прадьюмна и Анируддха. Из Санкаршаны появляется
Господь Нараяна, повелитель духовных планет Вайкунтх. Из Нараяны исходит
вторая четверичная экспансия (2-я чатур-вьюха) — Васудева, Санкаршана,
Прадьюмна и Анируддха.

Иногда Кришна нисходит или воплощается в материальном мире с
определённой целью. Такие воплощения называют аватара — «Тот, кто
нисходит». Ниже приводятся основные категории аватар Господа (ЧЧ, Мадхья
20.245-246):

1.  пуруша-аватары — воплощения, в которых Он осуществляет и
поддерживает материальное творение:

 - Маха-Вишну
 - Гарбходакашайи-Вишну
 - Кширодакашайи-Вишну

[start=2]
1.  лила-аватары — воплощения, в которых Он является, чтобы явить миру
Свои удивительные деяния, цель которых восстановить принципы религии,
наказать грешников, а также защитить преданных, сгорающих в разлуке с
Господом. Существует бесчисленное множество воплощений, относящихся к
этой категории, однако 10 из них (даша-аватара) являются основными и
приходят в материальный мир регулярно: Матсья, Курма, Вараха, Нрисимха,
Вамана, Парашурама, Рама, Баларама, Будда, Калки.
2.  гуна-аватары — воплощения, в которых Он управляет стихиями
материальной природы:

- «страсть» — Господь Брахма, творящий Вселенную
- «добродетель» — Господь Вишну, поддерживающий Вселенную
- «невежество» — Господь Шива, разрушающий Вселенную

3.  манвантара-аватары — воплощения, в которых Он задает общий свод
религиозных законов для всего человечества. Эти воплощения называют
Ману. В течении одного дня Брахмы (8.640.000.000 лет) сменяется 14 Ману.
4.  юга-аватары — воплощения, в которых Он регламентирует оптимальные
методы духовного развития для различных временных эпох (юга-дхарму). В
нашу эпоху, которая называется «Кали-юга», это воплощение Господа имеет
золотой цвет тела, Его имя Шри Чайтанья Махапрабху, и метод практики
данный Им (юга-дхарма) это совместное пение Святого имени Господа.
5.  шактиавеша-аватары — воплощения в образе живых существ,
уполномоченных на какие-то особые деяния.

Хотя все эти воплощения могут быть очень могущественны, тем не менее,
они отражают лишь часть качеств Кришны и играют подчинённую Ему роль.

[.lead]
Какими же качествами обладает Сам Кришна, и чем Он превосходит все
остальные воплощения?
