Urok 22                стр. 1 из 3

ВЕДИЧЕСКАЯ ФИЛОСОФИЯ (БАЗОВЫЙ КУРС)

Урок 22.

«ТВОРЕНИЕ МАТЕРИАЛЬНОГО МИРА»

Какие материальные первоэлементы возникают в результате соприкосновения
ложного эго с тремя гунами материальной природы?

Под влиянием времени, ложное эго, в сочетании с тремя гунами,
трансформируется в три вида:

1.  Вайкарика        — ложное эго в гуне благости
2.  Тайджаса        — ложное эго в гуне страсти
3.  Тамаса        — ложное эго в гуне невежества

Вайкарика.

В результате трансформации ложного эго в гуне благости возникает
материальный ум, который, порождая мысли и образы, формирует наши
желания. Ум произрастает из желания души. Если желание чисто, т.е.
бескорыстно, тогда ум, развивающийся из него, духовен. Если желание
нечисто, тогда из него развивается тонкая материя в гуне благости.
Согласно Шримад-Бхагаватам (11.2.38), функцией ума является принятие и
отвержение (санкалпа-викалпа). Материальный ум принимает и отвергает
что-либо, исходя из желания чувственного материального наслаждения.

Также результатом вайкарики является появление полубогов, управляющих
деятельностью тела (см. Шримад-Бхагаватам 2.5.30). Важно понять, что на
этом этапе Творения появляется лишь принцип полубогов, без конкретных
живых существ, исполняющих функции этих полубогов.

Тайджаса.

Это ложное эго в гуне страсти. Под влиянием времени тайджаса порождает
интеллект (разум). Функция интеллекта — анализировать/определять природу
объектов, попадающих в поле зрения живого существа и помогать его
чувствам. Проявление разума в живом существе можно определить по
признакам, описанным в Шримад-Бхагаватам 3.26.30:

«Сомнение, заблуждение, верное представление, память и сон, выполняющие
различные функции, считаются отличительными признаками интеллекта».

Дальнейшая трансформация ложного эго в гуне страсти приводит к
возникновению праны, жизненной энергии, а также пяти познающих и пяти
действующих чувств. Это объясняется в Шримад-Бхагаватам 3.26.31:

«Эго в гуне страсти порождает два вида чувств: познающие и действующие.
Действующие чувства связаны с жизненной энергией, а познающие — с
интеллектом».

[cols=",",]
|====================================================
|Действующие чувства |Познающие чувства
|Речь |Слух
|Руки |Осязание
|[multiblock cell omitted] |Зрение
|[multiblock cell omitted] |[multiblock cell omitted]
|[multiblock cell omitted] |Обоняние
|====================================================

Вкус
----

Вкус
1.  Действующие органы чувств связаны с жизненной энергией
2.  Познающие органы чувств связаны с интеллектом

Жизненная энергия, манипулируя действующими органами чувств,
поддерживает своё существование в теле. А разум, чтобы выстоять в
суровой борьбе за существование, прибегает к помощи познающих органов
чувств. Так как борьба за существование — это проявление гуны страсти,
то, следовательно, все органы чувств, а также управляющие ими разум и
жизненная энергия (прана), являются порождением и побочными результатами
деятельности ложного эго в гуне страсти. Шрила Прабхупада поясняет в
комментарии к Шримад-Бхагаватам 3.26.31:

«…оба вида чувств — познающие и действующие — порождены эго в гуне
страсти, а поскольку для того, чтобы действовать и познавать, органам
чувств необходима энергия, то жизненная энергия, или энергия жизни, тоже
возникает из эго в гуне страсти. Поэтому в жизни мы видим, что люди,
находящиеся преимущественно под влиянием гуны страсти, очень быстро
достигают материального благополучия. Веды, чтобы побудить человека к
материальной деятельности, рекомендуют стимулировать его сексуальное
желание, поскольку секс является олицетворением жизни в гуне страсти. Но
те, кто стремятся к духовному прогрессу, должны полностью избавиться от
влияния гуны страсти и достичь уровня гуны благости…».

Тамаса.

Эго в гуне невежества называется тамасой. Трансформируясь, под
воздействием времени, тамаса порождает пять материальных элементов, пять
объектов этих элементов и пять органов для их восприятия. Процесс
создания грубых элементов, их объектов и органов восприятия начинается с
более тонких и развивается к более грубым:

1.  Эфир. Самым тонким объектом грубых материальных элементов является
звук. Звук даёт начало эфиру. Иногда говорится, что эфир — это
пространство. Кроме того, звук является источником органа слуха — уха.
Мудрецы, обладающие истинным знанием, определяют звук, как субстанцию,
представляющую собой тонкую форму эфира, и которая передаёт
представление о предмете и указывает на присутствие говорящего. Функции
и признаки эфира заключаются в том, что он предоставляет место для
внешнего и внутреннего бытия всех живых существ, то есть, является полем
деятельности:

1.  Жизненного воздуха
2.  Чувств
3.  Ума

Из этого можно видеть, как тонкий ум связан с грубой материей. Другими
словами, деятельность ума или психическая деятельность, проявляющаяся в
мышлении, эмоциях и желаниях, протекает в эфире (пространстве). Когда
человек умирает, умственная деятельность, обладающая тонкой формой, со
временем преобразуется в грубую форму.

1.  Воздух. Сотворённый звуком эфир под влиянием времени подвергается
следующей трансформации, и на свет появляется тонкий по природе объект
осязания — касание, а из него образуется воздух и орган осязания.
Мягкость и твёрдость, холод и тепло — таковы характеристики,
воспринимаемые осязанием, которое представляет собой тонкую форму
воздуха. Воздух отвечает за движение, смещение и нормальное
функционирование всех органов чувств, он также предоставляет возможность
приблизиться к объектам звука и переносит другие объекты чувств.
2.  Огонь. С течением времени в процессе эволюции воздух
трансформируется в огонь, который приобретает форму, и глаз,
воспринимающий форму и цвет огня. Форму и цвет мы можем воспринимать
глазами при условии наличия солнца, сияние которого является чувственным
объектом глаза.
3.  Вода. Повинуясь высшей воле, огонь подвергается дальнейшей
трансформации, порождая тонкий по природе объект вкуса. Из вкуса
возникает вода, а также язык, который ощущает вкус. Поскольку вкус
возникает из воды, язык всегда увлажнён слюной. Смешиваясь с различными
веществами, изначально единый вкус принимает различные формы, становясь
вяжущим, сладким, горьким, острым, кислым и солёным. Также вода
характеризуется способностью увлажнять другие вещества, приносить
чувство удовлетворения, поддерживать жизнь, размягчать предметы,
уменьшать жар и освежать, утоляя жажду. Благодаря воде происходит
смешение элементов. Чтобы замесить тесто, к муке добавляют воду; чтобы
построить дом, требуются кирпичи, для производства которых используется
вода. Огонь, воздух и вода являются элементами, связующими всё
материальное мироздание.
4.  Земля. Далее, под влиянием высшей воли, вода порождает тонкий
элемент запаха. В результате появляются земля и орган обоняния, с
помощью которого мы ощущаем всю гамму присущих земле запахов.

Так появляются пять грубых материальных элементов (эфир, воздух, огонь,
вода и земля), пять объектов этих элементов (звук, касание, форма, вкус
и запах) и пять органов их восприятия (ухо, орган осязания, глаз, язык и
нос). Каждый последующий материальный элемент сохраняет качества
предыдущего:

1.  Эфир         — звук
2.  Воздух         — звук, касание
3.  Огонь         — звук, касание, форма
4.  Вода        — звук, касание, форма, вкус
5.  Земля         — звук, касание, форма, вкус, запах

Нетрудно заметить, что земля является средоточием всех качеств, присущих
также остальным элементам. Всего земля обладает пятью качествами грубых
элементов, у воды их четыре, у огня — три, у воздуха — два, а небу
присуще только одно качество — звук. Так, исследуя качества различных
элементов, проницательный человек может увидеть причину их появления.

В Шримад-Бхагаватам 3.26.49 говорится:

«Поскольку причина присутствует и в следствии, признаки причины можно
обнаружить в следствии. Вот почему только земля содержит в себе
отличительные качества всех остальных элементов».

Итак, причиной появления земли является вода, причиной воды — огонь,
причиной огня — воздух, причиной воздуха — эфир, причиной эфира — звук,
а причиной звука — эго в гуне невежества (тамаса). Эго в гуне невежества
возникает благодаря взгляду Маха-Вишну, который активизирует три гуны
материальной природы и привносит в махат-таттву живые существа. Причина
появления Маха-Вишну — Второй Санкаршана, причина Второго Санкаршаны —
Господь Нараяна, причина Нараяны — Первый Санкаршана, причина Первого
Санкаршаны — Баларама, а причина Баларамы — Господь Кришна, Верховная
Божественная Личность. Поэтому Кришна является причиной всех причин.

Любой разумный человек, проследив динамику трансформации материального
мира из непроявленного состояния в проявленное, придёт к пониманию, что
это возможно только благодаря присутствию высшей воли, воли Бога. Без
Его воли материальные элементы не способны даже соединиться вместе, не
говоря уже о том, чтобы иметь определённое предназначение.

Вот что об этом говорится в Шримад-Бхагаватам 3.26.18:

«Являя Свои энергии, Господь, Верховная Божественная Личность, соединяет
различные материальные элементы, находясь внутри них в образе Сверхдуши
и вне их в образе вечного времени».

Важно отметить, что весь процесс Творения происходит от тонкого к
грубому. Этот принцип находит свое отражение как 2-ой закон
термодинамики, принятый современной наукой. Самая тонкая реальность —
духовная, поэтому источником материального мира является, в конечном
итоге, дух.

Как осуществляется вторичное Творение — висарга?

Далее Господь Брахма (первое живое существо во вселенной), наделённый
особыми полномочиями соединять материальные первоэлементы в
разнообразные формы, осуществляет вторичный этап Творения. Он медитирует
на духовные звуки, олицетворяющие собой духовные формы и, видя эти
формы, творит по их подобию и на их основе материальные формы. «Все
многообразные искаженные материальные формы имеют свой точный духовный
прообраз в духовном мире» (Шримад-Бхагаватам 2.6.1, комм.). Так
постепенно во вселенной появляются 8400000 форм жизни, в которые, в
соответствии со своим уровнем сознания и деятельностью в прошлом,
воплощаются обусловленные живые существа.

Как проявляется во вселенной время?
