Urok 24                стр. 1 из 2

ВЕДИЧЕСКАЯ ФИЛОСОФИЯ (БАЗОВЫЙ КУРС)

Урок 24.

«КРИШНА — ЦЕНТР ВСЕХ ДУХОВНЫХ ВЗАИМООТНОШЕНИЙ»

Какие виды взаимоотношений возможны с Богом?

В этом уроке мы кратко опишем внутреннюю энергию Кришны, которая
представляет собой весь духовный мир. Там, на бесчисленных духовных
планетах, Господь пребывает в Своих разнообразных духовных формах,
окруженный Своими вечными спутниками. Все обитатели духовного мира
вступают с Господом и друг с другом в различные духовные
взаимоотношения, которые доставляют им безграничное счастье. Все эти
виды взаимоотношений представляют собой различные формы любовного
взаимообмена, являющегося сущностью духовного мира. И всё многообразие
духовного мира возникает лишь для того, чтобы этот любовный взаимообмен
между Кришной и Его бесчисленными преданными мог проявиться.

Таким образом, каждое живое существо в духовном мире связано с Господом
своими, неповторимыми отношениями, которые называются раса. В 20-й главе
«Нектара Преданности» Шрила Прабхупада дает следующее определение расы:
«…Расой называют особое любовное состояние, в котором находится
преданный, наслаждаясь своими любовными отношениями с Верховной
Личностью Бога…».

И хотя все эти отношения неповторимы, тем не менее, их можно
подразделить на 5 основных видов:

1.  Дасья-раса                — отношения служения
2.  Шанта-раса        — нейтральные отношения
3.  Сакхья-раса        — дружеские отношения
4.  Ватсалья-раса        — родительские отношения
5.  Мадхурья раса        — супружеские отношения

Каждый преданный связан с Кришной одним из этих пяти видов отношений, в
соответствии со своей любовной привязанностью к Нему, называемой рати.
Помимо этих пяти, существует еще семь второстепенных видов
взаимоотношений, которые усиливают основные:

1.  Хасйа                — смех
2.  Адбхута                — удивление
3.  Вира                — геройство
4.  Каруна                — милость, сострадание
5.  Раудра                — гнев
6.  Бхайянака                — ужас, страх
7.  Бибхатса                — потрясение, отвращение

В комментарии к Шримад-Бхагаватам 1.1.3 Шрила Прабхупада пишет:
«…Совокупность этих рас называется любовью. Любовь проявляется в первую
очередь в поклонении, служении, дружбе, родительской привязанности и
супружеской любви. Когда же эти пять видов проявлений отсутствуют,
любовь косвенно выражается в виде гнева, удивления, смеха, геройства,
страха, потрясения и так далее…»

Как понять какие отношения у меня с Кришной и как эти отношения
развиваются?

 

У каждого живого существа уже есть свои неповторимые отношения с
Кришной, однако, находясь в обусловленном состоянии, оно утрачивает
память об этом. Поэтому, пока сознание живого существа нечисто,
невозможно просто вообразить себе эти отношения и таким образом достичь
их. Необходимо очистить своё сознание и тогда эти отношения проявятся
сами собой. Поэтому процесс практики Сознания Кришны — это процесс
постепенного очищения сознания, который естественно приведёт к
пробуждению и постепенному вспоминанию Ваших утраченных отношений с
Кришной. Если правильно следовать процессу, то эти отношения постепенно
разовьются.

Как происходит это постепенное развитие, объясняет великий святой
Рамананда Рой в беседе с Господом Чайтаньей (см. «Учение Шри Чайтаньи,
глава 29):

«…Затем Рамананда Рой объяснил постепенный процесс, с помощью которого
развивается чистая любовь к Кришне. Он отметил, что живое существо
связано с Верховной Личностью Бога той формой отношений, которая
единственно подходит для него. На самом деле взаимоотношения с Верховным
Господом, начинаясь с отношений господина и слуги, развиваются в дружбу,
родительскую привязанность и супружескую любовь. И тот, кто достиг своих
индивидуальных взаимоотношений с Верховной Личностью Бога, должен
считаться достигшим самых лучших для него взаимоотношений. Однако,
исследовав все эти духовные взаимоотношения, можно увидеть, что
нейтральные отношения на стадии реализации брахма-бхуты идут первыми.
Когда человек начинает считать Бога своим господином, а себя — Его
слугой, эти взаимоотношения углубляются, и при их дальнейшем развитии
человек становится другом Верховного Господа; еще большая степень их
развития достигается, когда человек становится его отцом. Таким образом,
взаимоотношения углубляются от дружбы до любви и, наконец, перерастают в
супружескую любовь, которая является высшим видом взаимоотношений с
Господом…».

Итак, взаимоотношения развиваются постепенно, начиная с нейтральных:

[cols=",",]
|=======================================================================
|[multiblock cell omitted] |[multiblock cell omitted]

|Нейтральные |Чистота сознания (всё и всех видит в связи с Кришной)

|Слуги и господина |Чистота сознания + служение

|Дружеские |Чистота сознания + служение + равенство

|Родительские |Чистота сознания + служение + равенство + забота

|Супружеские |Чистота сознания + служение + равенство + забота + полная
самоотдача
|=======================================================================

Вид взаимоотношений
-------------------

Вид взаимоотношений
Развиваемые качества
--------------------

Развиваемые качества
Таким образом, семя Ваших вечных взаимоотношений с Кришной уже есть у
Вас в сердце. Если Вы будете поливать это семя, в процессе практики
слушания и повторения Харе Кришна маха-мантры и повествований об имени,
форме, качествах и играх Кришны, тогда эти отношения проявятся в должный
срок.

В духовном мире есть множество планет. Какие виды взаимоотношений живых
существ с Богом проявляются на этих планетах?

В уроке №12 мы уже описывали различные планеты духовного мира,
различающиеся по степени увеличения аспекта мадхурьи (сладости) Господа.
Чем больше проявлен аспект мадхурьи Господа, тем выше считается планета.
Этот аспект мадхурьи проявляется во взаимоотношениях Господа с Его
преданными. Чем более близкие отношения, тем более сладостны они. Таким
образом, 5 основных рас или отношений с Господом проявляются следующим
образом:

1.  Вайкунтха — Проявляются шанта-раса (нейтральные отношения) и
дасья-раса (отношения слуги и Господина)
2.  Айодхья — В отличие от планет Вайкунтх, отношения служения,
дасья-раса, здесь становятся более близкими, и изредка даже проявляются
как почтительная дружба (гаурава-сакхья-раса).
3.  В Двараке и Матхуре — проявляются отношения служения (дасья-раса),
дружеские отношения (сакхья-раса), родительские отношения
(ватсалья-раса) и супружеские отношения (мадхурья-раса), но смешанные с
осознанием величия Кришны, поскольку Кришна там является царём.
4.  Вриндаван — Во Вриндаване взаимоотношения с Кришной в дасья-,
сакхья-, ватсалья- и мадхурья-расах достигают максимальной зрелости. В
отличии от предыдущих планет, эти взаимоотношения не ограничены
осознанием Верховного положения Кришны. Его слуги, друзья, родители и
возлюбленные движимы только спонтанной, беспримесной любовью. Несмотря
на то, что Кришна является изначальной Личностью Бога, преданные во
Вриндаване видят Его просто как мальчика-пастушка. Это позволяет им
проявлять ничем не ограниченные чувства к Кришне. Поэтому, в отличии от
других мест духовного мира, во Вриндаване проявляются особые сокровенные
отношения, в которых преданный находится в равных отношениях с Кришной
или даже занимает более высокое или покровительственное положение,
связывая Господа узами своей безграничной любви. Поэтому Вриндаван —
самая сокровенная обитель Господа.

В заключении важно отметить, что все описанные виды отношений проявлены
также и в материальном мире, однако они осквернены представлением о
жизни, как о жизни тела, и поэтому лишены чистоты и бескорыстия. И хотя
внешне духовные отношения напоминают отношения живых существ в
материальном мире, они имеют совершенно иную природу. Поэтому ни в коем
случае нельзя оценивать духовные взаимоотношения на основе своего
материального опыта. Природу духовных отношений нужно постигать с
большой осторожностью. Понять их может только чистый сердцем человек,
наделённый истиной верой, которая обретается в общении с чистыми
преданными Кришны. Поэтому человеку, вставшему на духовный путь,
рекомендуется избегать общения с материально устремленными людьми и
стремиться в общество таких преданных.

Каково отличие материального мира от духовного мира, и материальных
отношений от духовных?
