== Урок 15. КРИШНА — ОБЛАДАТЕЛЬ ВСЕХ ЭНЕРГИЙ

[.lead]
Какими же энергиями обладает Кришна?

Веды утверждают, что Кришна, являясь Абсолютом, обладает безграничными
энергиями. Одно из качеств Верховной Личности называется сатйа-санкалпа,
что означает следующее: любое Его желание или намерение всегда в
совершенстве выполняется Его разнообразными энергиями. Его желание — это
уже свершившийся факт.

Это подтверждается в «Шветашватара Упанишад» 6.8:

на тасйа карйам каранам ча видйате +
на тат-самаш чабнйадикаш ча дришйате +
парасйа шактир вивидхайва шруйате +
свабхавики джнана-бала-крийа ча

«Верховному Господу ничего не нужно делать Самому — всё выполняют Его
разнообразные энергии. На свете нет никого равного Ему или более
великого, чем Он».

Таким образом, Верховному Господу нет необходимости тяжело трудиться для
того, чтобы что-то происходило в духовном и материальном мироздании. Всё
приводится в движение безграничными энергиями Кришны, которые действуют
в соответствии с Его желанием и волей.

Его энергии бесчисленны, божественны, вечны и составляют всё сущее.
Энергии Кришны всегда находятся с Ним, Ему не нужно делать что-либо,
чтобы приобрести их. И по количеству, и по качественному составу Его
энергии бесконечны и постоянно расширяются. Поэтому их невозможно
описать полностью.

[.lead]
Если Его энергии безграничны, как же можно понять их?

Для более ясного понимания Веды подразделяют энергии Кришны на три
основные категории (Чайтанья Чаритамрита, Мадхья 20.111):

кришнера свабхавика тина-шакти-паринати

чит-шакти, джива-шакти, ара майа-шакти

«Господь Кришна обладает тремя энергетическими преобразованиями, которые
известны как:

1.  Антаранга-шакти Внутренняя энергия (духовная или
высшая энергия).
2.  Татастха-шакти Пограничная энергия (живые существа
или души).
3.  Бахиранга-шакти Внешняя энергия (материальная или
низшая энергия).

Духовный мир является проявлением внутренней энергии. Материальный мир —
проявление внешней энергии. Живые существа относятся к пограничной
энергии. Они вечные духовные частички, но, являясь очень маленькими
(ану) они не могут быть независимы и потому склонны принимать прибежище
либо духовного, либо материального миров.

В каждой из этих 3-х реальностей присутствуют другие три вида энергий, о
которых уже упоминалось ранее:

1.  Энергия вечности (сат, или сандхини).
2.  Энергия знания (чит, или самвит).
3.  Энергия блаженства (ананда, или хладини).

В результате воздействия энергий вечности, знания и блаженства на
внутреннюю, пограничную и внешнюю энергии, возникает все творение
Господа:

