Urok 14                        стр. 1 из 2

  ВЕДИЧЕСКАЯ ФИЛОСОФИЯ (БАЗОВЫЙ КУРС)

Урок 14.

«БЕЗГРАНИЧНОЕ ВЕЛИКОДУШИЕ И ЩЕДРОСТЬ

ГОСПОДА ЧАЙТАНЬИ»

Что это за воплощение Кришны — Шри Чайтанья, и почему Его называют Самым
милостивым?

Итак, мы описали два настроения — айшварья (безграничное величие) и
мадхурья (безграничная сладость), которые проявляет Верховная
Божественная Личность. Наиболее привлекательное из них — это настроение
мадхурьи. Сладостные отношения Кришны с близкими спутниками во
Вриндаване доставляют Ему безграничное наслаждение. Желая понять любовь,
которую испытывает Его чистый преданный по отношению к Нему, Кришна
приходит как Шри Чайтанья, приняв настроение и чувства самой возвышенной
преданной в духовном мире — Шримати Радхарани. Так Кришна и Радхарани
сливаются в одной форме Шри Чайтаньи, имеющей цвет, подобный цвету
расплавленного золота. Играя роль преданного, Кришна наслаждается
любовью к Самому Себе и в тоже время щедро раздает эту любовь всем,
независимо от того, обладает человек необходимыми качествами или нет,
заслуживает он такого дара или нет, просит он или не просит. Поэтому Шри
Чайтанью сравнивают с опьяненным царем, который щедро раздает всем свои
богатства. Это особое настроение Господа называется  аударья —
«безграничное сострадание, великодушие и щедрость».

Поскольку Господь Чайтанья, в отличии от всех других воплощений, щедро
одаривает всех кришна-премой — чистой любовью к Кришне, не ставя при
этом никаких условий, Его называют «Самым милостивым воплощением»:

намо маха-ваданйайа

кришна-према-прадайа те

кришнайа кришна-чайтанья-

намне гаура-твише намаха

«О самое милостивое воплощение Господа! Ты — Сам Кришна, явившийся в
облике Шри Кришны Чайтаньи Махапрабху. Ты, чьё тело приобрело золотистый
цвет тела Шримати Радхарани, щедро раздаешь чистую любовь к Кришне. В
глубоком почтении мы склоняемся перед Тобой».

Когда и с какой целью Шри Чайтанья Махапрабху является в материальном
мире?

 Господь Чайтанья приходит очень редко — только один раз в течении
периода времени равного 8.640.000.000 земных лет. Поэтому это очень
редкая возможность обрести Его милость. К счастью для нас, в последний
раз Его игры проходили пятьсот лет назад (1486 – 1534 гг.). В
соответствии с предсказанием Самого Господа, на земле должен был
проявиться и просуществует десять тысяч лет «Золотой век» (век
добродетели, мудрости и религиозности). Этот «Золотой век» начался с
момента распространения миссии Господа Чайтаньи по всему миру (примерно
в 1996 году). В течение ближайших десяти тысяч лет этого благоприятного
периода бесчисленное количество живых существ будет возвышаться до
духовного мира, соприкасаясь с движением Господа Чайтаньи и обретая,
таким образом, Его беспричинную милость.

Итак, Шри Чайтанья Махапрабху является в материальном мире с двумя
целями: насладиться любовью к Самому Себе и щедро одарить других этой
любовью. Где бы ни появлялся Верховный Господь, все воплощения, энергии
и спутники всегда сопровождают Его. Поэтому когда Господь Чайтанья
появился на земле, вместе с Ним пришли и Его спутники, которые помогали
Ему в играх. Прежде всего, это Его непосредственная экспансия Шри
Нитьянанда Прабху (воплощение Баларамы), Его воплощение Шри Адвайта
Прабху (совместное воплощение Маха-Вишну и Сада-Шивы), Его внутренняя
энергия Шри Гададхара Прабху (воплощение Шримати Радхарани)  и Его
пограничная энергия Шривас Тхакур (воплощение великого преданного Нарады
Муни). Вместе с Господом Чайтаньей их называют Панча-таттва (панча —
«пять», таттва — «истина»), или пятью проявлениями Абсолютной Истины.
Поскольку эти пять истин всегда пребывают вместе, то только поклонение
им всем является полным поклонением Богу. Опишем же эти пять
божественных проявлений более подробно:

Господь Шри Чайтанья Махапрабху.

Господь Чайтанья — это изначальный Верховный Господь Кришна, который
пришел как преданный, чтобы проповедовать славу повторения Святого
Имени. Проявляя безграничную любовь к Богу, Шри Чайтанья принял
настроение Шримати Радхарани, величайшей преданной и попытался  ощутить
то, что переживает Она. По-другому Господа Шри Чайтанью называют
Махапрабху, что означает — «Великий господин».

Господь Нитьянанда.

Шри Нитьянанда — это первая экспансия Кришны — Господь Баларама. Также
как и  Баларама, Господь Нитьянанда всегда пребывает в настроении слуги
Всевышнего. В духовном мире Он повелевает энергиями знания и бытия.
Нитьянанда - предводитель всех живых существ и Он распространяет Себя в
три пуруша-аватары, начиная с Маха-Вишну, который творит этот
материальный мир. Будучи изначальным духовным учителем, Он всюду
проповедовал славу воспевания Святого Имени Кришны и давал милость даже
самым последним грешникам. Мы можем приблизиться к Господу Чайтанье,
только обретя милость Нитьянанды Прабху.

Господь Шри Адвайта Ачарья.

Адвайта Ачарья — это воплощение Господа Маха-Вишну, который является
творцом всех материальных вселенных. Он — источник всех аватар,
воплощений Господа, приходящих во вселенную, чтобы освободить падшие
души. В играх Шри Чайтаньи Он играл роль преданного. Именно Адвайта
Ачарья был тем,  чьё сострадание к обусловленным душам заставило Господа
Чайтанью прийти в этот мир, чтобы спасти невежественных обитателей этого
века.

Господь Гададхара.

Господь в духовном мире не одинок. Распространяя Себя во множество форм,
Он наслаждается взаимоотношениями со Своими энергиями, шакти, которые
бывают двух видов. К первому виду относятся достигшие совершенства души,
относящиеся к джива-шакти — пограничной энергии. Они служат Господу в
духовном мире как Его спутники. Ко второму виду относятся особые
преданные Господа, относящиеся к хладини-шакти — внутренней энергии.
Подобно душам они также служат Господу, но при этом обладают гораздо
большим могуществом. Главная среди них — Шримати Радхарани. Когда Кришна
пришел в этот мир в облике Господа Чайтаньи, Он играл роль преданного, а
Его энергия наслаждения, хладини-шакти, пришла в облике Гададхары.
Гададхара также действовал как безупречный преданный, поэтому его
отношения с Господом не выглядели супружескими, как это происходит в
играх во Вриндаване. Но не смотря на это Господь Чайтанья и Гададхара
были неразлучны, где бы Господь не проводил Свои игры.

Шривас Тхакур.

Шривас Тхакур представляет безупречных живых существ, джив, посвятивших
жизнь служению Господу. Число совершенных душ неизмеримо. Все они с
чистой любовью и преданностью служат Господу и Его супруге. Нарада Муни,
вечный проповедник и великий преданный, в играх Господа Чайтаньи явился
как Шривас. Он всем сердцем служил Господу Чайтанье, Нитьянанде и
Адвайта Ачарье. Именно в доме Шриваса Тхакура началось движение
санкиртаны Господа Чайтаньи. В течении целого года Махапрабху со своими
спутниками каждый вечер собирались в доме Шриваса, чтобы за закрытыми
дверями петь Святые имена Кришны. В один из таких дней Господь Чайтанья
раскрыл Шривасу и другим преданным Свою божественную суть. В течении
двадцати одного часа преданные, ликуя,  поклонялись Господу, громко пели
Его Святые Имена и предлагали Ему пышное поклонение.

Итак, явившись в этом мире, Господь Чайтанья раскрыл скрытый смысл игр
Господа Кришны и объяснил, как человек может постичь их. Поэтому, чтобы
понять сокровенный смысл игр Шри Радхи и Шри Кришны во Вриндаване,
необходимо смотреть на эти игры через призму игр и учения Шри Чайтаньи.
Являясь юга-аватарой (воплощением, установившим высшую религию для этого
века), Господь Чайтанья учил всех петь и повторять маха-мантру:

ХАРЕ  КРИШНА    ХАРЕ  КРИШНА          КРИШНА  КРИШНА    ХАРЕ  ХАРЕ
------------------------------------------------------------------

ХАРЕ  РАМА    ХАРЕ  РАМА         РАМА  РАМА    ХАРЕ  ХАРЕ
---------------------------------------------------------

Однако без милости Господа Чайтаньи и Его спутников нам будет очень
трудно освободиться от оскорблений во время повторения. Поэтому, прежде
чем повторять Харе Кришна, необходимо сначала воззвать к милости
Панча-таттвы, повторяя  следующую молитву:

(джайя) шри-кришна чайтанья прабху нитьянанда

шри-адвайта гададхара шривасади-гаура-бхакта-вринда

«Я в глубоком почтении склоняюсь перед Шри Кришной Чайтаньей, Прабху
Нитьянандой, Шри Адвайтой, Гададхарой, Шривасой и всеми остальными
последователями Господа».

Шри Кришна Чайтанья настолько милостив, что прощает ошибки и
оскорбления, которые можно совершить в процессе повторения Святого
имени. Поэтому тот, кто всегда взывает к милости Шри Чайтаньи и Его
спутников преодолеет все препятствия на духовном пути и постепенно
осознает Кришну — Верховную Божественную Личность.

Каждая личность обладает энергией, позволяющей выполнять свои желания и
действовать. Какими же энергиями обладает Кришна?
