Rukovodstvo dlya prepodavaniya                стр. 1 из 18

ВЕДИЧЕСКАЯ ФИЛОСОФИЯ (БАЗОВЫЙ КУРС)

РУКОВОДСТВО ДЛЯ ПРОВЕДЕНИЯ 2-Й ЧАСТИ КУРСА

Урок №9.

«БХАГАВАН — ВЕРХОВНАЯ БОЖЕСТВЕННАЯ ЛИЧНОСТЬ — ЯВЛЯЕТСЯ ВЫСШИМ
ПРОЯВЛЕНИЕМ АБСОЛЮТНОЙ ИСТИНЫ»

Цель урока №9: Пробудить у слушателя Курса желание стать преданным
Господа, дав понимание трех аспектов Абсолюта, как трех различных
ступеней Его постижения. Нет необходимости идти постепенным путем
(сначала реализация Брахмана, затем Параматмы, а уж потом Бхагавана).
Нет, нужно сразу сосредоточиться на постижении Бхагавана, ибо Его
реализация включает два предыдущих аспекта. Практика позволяющая достичь
этого —  бхакти-йога — или любовное преданное служение.

Внутренняя логика Урока:

Кто же этот изначальный Верховный Господь, обладающий самым полным,
совершенным знанием? Является ли Он личностью или же Он безличен?

1.  Существует три ступени постижения Бога:

1.  Безличный Брахман. Тем, кто стремится постичь Его в этом аспекте,
Бог предстает в виде безличного сияния, исходящего от Его
трансцендентного тела.  Люди, стремящиеся к постижению брахмана, это
разачорованные в материальном мире души. Их желание – это избавление от
страданий материального существования. Они хотят достичь состояния
спокойствия и умиротворение, которое дает достижение уровня реализации
Брахмана.
2.  Параматма (парама – «высшая», атма – «душа») Тем, кто стремится
постичь Его в этом аспекте, Бог предстает в четырёхруком образе, который
одновременно пребывает в сердце каждого живого существа и каждом атоме
творения. Параматма поддерживает все материальное творение, сопровождая
обусловленные души. Люди, стремящиеся к постижению Параматмы и
установлению связи с Ней, желают обрести откровения, исходящие от
Параматмы и мистические силы.
3.   Бхагаван – Верховная Божественная Личность. Человек, постигший Бога
в этом аспекте, погружается в океан духовного блаженства любовного
взаимообмена с Ним в Его надмирных играх. Тех, кто стремится к
постижению этого аспекта, интересует Сам Кришна как Личность. Поэтому
такой преданный желает только отношений (расы) с Кришной.

1.  Верховная Божественная Личность — это сат-чит-ананда-виграха — форма
(виграха), исполненная вечности (сат), знания (чит) и блаженства
(ананды). Реализация Брахмана дает возможность постичь аспект сат —
«вечность»; Реализация Параматмы — аспекты сат — «вечность» и чит —
«знание»; И только реализация Бхагавана позволяет постичь Бога во всей
полноте — сат-чит-ананда-виграха. Каждый последующий аспект включает в
себя предыдущий.
2.  Бхактивинода Тхакур объясняет, что Брахман — это Бог без энергий,
Параматма — Бог, повелевающий материальными энергиями, Бхагаван — это
Бог, повелевающий и материальными и духовными энергиями.
3.  Реализации Брахмана достигают гьяни, практикующие гьяна-йогу, суть
практики которой заключается в том, чтобы в процессе размышлений
научиться определять, чем дух не является. Реализации Параматмы
достигают йоги, прошедшие весь путь восьмиступенной мистической йоги
(аштанга-йога: ашта – «восемь», анга – «ступеней»). Бхагаван открывается
только бхактам (преданным Бога), которые с любовью и преданностью служат
Господу, желая доставить Ему удовольствие.
4.  Для иллюстрации этих трех аспектов Абсолютной Истины можно
использовать аналогию с солнечным светом, солнечным диском и богом
Солнца, или аналогию с приближением к горе (эти аналогии приводятся
ниже).

Итак, подводя итог, обобщим все в таблице:

[cols=",,,,,,",]
|=======================================================================
|[multiblock cell omitted] |[multiblock cell omitted]
|[multiblock cell omitted] |[multiblock cell omitted] |Желания
|Проявление Бога: |Описание Бога:

|Брахман |сат – вечность |Гьяна-йога |гьяни |[multiblock cell omitted]
|Бог без энергий |Безличное сияние, исходящее от тела Бога

|Параматма |[multiblock cell omitted] |Аштанга-йога |йоги |Желание
откровений и мистических сил |[multiblock cell omitted] |Форма Бога,
пребывающая в сердце каждого ж. существа и в каждом атоме творения.

|Бхагаван |[multiblock cell omitted] |Бхакти-йога |бхакты |Желание
взаимодейст-вовать с Самим Богом и преданно служить Ему
|[multiblock cell omitted] |Форма Господа, исполненная ананды -
блаженства взаимоотношений с любящими преданными в вечных
трансцен-дентных играх
|=======================================================================

Что происходит с человеком, который достиг лишь частичной реализации
Абсолюта, - реализации Брахмана или Параматмы? Удовлетворён ли он
достигнутым совершенством и заканчивается ли на этом его духовные
устремления?

1.  Провести анализ всех трёх ступеней реализации Бога: Брахмана,
Параматмы и Бхагавана. На ступенях реализации Брахмана и Параматмы
трансценденталист будет ощущать чувство неполноты и незаконченности пути
совершенствования. Это чувство будет подталкивать его либо вновь
опуститься на уровень материальных отношений (ища удовлетворение вне
себя), либо стремиться к дальнейшему совершенствованию (ища причину
внутри себя). Обычно те, кто опускается на материальный уровень с уровня
реализации Брахмана, начинают заниматься благотворительностью и
миссионерством. Те, кто опускаются на материальный уровень со ступени
реализации Параматмы, начинают демонстрировать мистические силы и
зачастую объявляют себя богом.
2.  Таким образом, стремления к счастью (ананде), знанию (чит) и
вечности (сат) заложены в самой природе души. Поэтому, до тех пор, пока
душа не реализует аспект Бхагавана, она будет испытывать духовное
чувство неполноты, которое будет подталкивать ее к дальнейшему поиску.
Даже те, кто достигли реализации Брахмана и Параматмы, продолжают поиск.
Однако не всегда этот поиск приводит к прогрессу. Зачастую такие люди
спускаются на материальный уровень и постепенно деградируют.

Вывод: Путь бхакти-йоги наиболее безопасный и возвышенный метод, который
позволяет сразу развивать взаимоотношения с Личностью Бога – Бхагаваном
и т.о. полностью удовлетворить потребности души.

Каково значение слова Бхагаван и какое имя лучше всего описывает Его?
Почему существует много Имен Бога?

Приложения к уроку 9:

1.  Аналогия с солнцем:

В Бхагавад-Гите 2.2 Шрила Прабхупада так описывает эти 3 ступени
постижения Бога: «Эти три божественных аспекта можно объяснить на
примере Солнца, у которого также существует три различных аспекта –
солнечный свет, солнечный диск и планета Солнце. Тот, кто изучает
солнечный свет, находится на первой ступени процесса познания.
Поднявшись на следующую ступень, человек познает солнечный диск, однако
самым развитым является тот, кто достиг планеты Солнце. Учеников,
довольствующихся изучением свойств солнечного света, его вездесущности и
ослепительного безличного сияния можно сравнить с человеком, способным
постичь лишь один аспект Абсолютной Истины — аспект Брахмана. Тот, кто
более развит, обладает знанием о солнечном диске. Он подобен человеку,
постигшему следующий аспект Абсолютной Истины — аспект Параматмы. А
того, кто проник в сердце планеты Солнца, сравнивают с человеком,
который осознал личностный аспект высшей Абсолютной Истины. Вот почему
бхакт или трансценденталистов, постигших Верховную Абсолютную Истину в
аспекте Бхагавана, считают лучшими среди трансценденталистов, хотя все,
кто изучает Абсолютную Истину, направляют свои усилия на один и тот же
объект. Свет Солнца, солнечный диск и сама планета Солнце неотделимы
друг от друга, однако тех, кто изучает эти разные аспекты, нельзя
отнести к одной и той же категории».

1.  Аналогия с горой:

Когда человек приближается к горе, вначале он видит нечто бесформенное,
покрытое дымкой. Затем, подойдя ближе, он видит, что на горе растут
деревья. Но лишь подойдя вплотную к горе, он может увидеть, что на
склонах этой горы бегают животные, а в лесах, покрывающих ее, летают
птицы, бабочки и жуки. Только подойдя так близко, человек может во всей
полноте воспринять гору.

 Точно также, человек, находящийся от Бога далеко, воспринимает Его как
безличный Брахман. Тот, кто до некоторой степени приблизился к Нему —
может увидеть Его духовную форму. Но преданным Господь открывается как
Некто, обладающий качествами и совершающий бесконечные, необычайно
привлекательные и исполненные блаженства игры со Своими преданными.

Урок №10.

«КРИШНА — ВЕРХОВНАЯ БОЖЕСТВЕННАЯ ЛИЧНОСТЬ,

ОН — ИСТОЧНИК ВСЕХ ВОПЛОЩЕНИЙ»

1. 

Внутренняя логика Урока:

Что означает санскритское слово «Бхагаван»?

1. 

Каким именем называть Бхагавана — Верховную Личность?

1. 

Цитаты из шастр подтверждающие, что Кришна Верховная Личность Бога –
Бхагаван:

Перечислить цитаты и подчеркнуть следующее:

1. 

Люди называют Бога различными именами. Означает ли это что есть много
Богов?

1. 

Какие бывают воплощения Бога?

1.  Те воплощения, которые обладают всеми достояниями Верховной Личности
Бога, относятся к категории вишну-таттва, то есть относящиеся к той же
категории Абсолютной Истины, что и Сам Кришна. Перечислите основные
Вишну-таттвы.
2.  Иногда Кришна нисходит или воплощается в материальном мире с
определенной целью. Такие воплощения называют аватара — «Тот, кто
нисходит». Перечислить 6 видов аватар.

1.  Сделать важное утверждение, как переход к следующему уроку: «Хотя
все эти воплощения могут быть очень могущественны, тем не менее, они
отражают лишь часть качеств Кришны и играют подчиненную Ему роль».

Какими же качествами обладает Кришна, и чем Он превосходит все остальные
воплощения?

 

Урок №11.

«КРИШНА — ИСТОЧНИК ВСЕХ КАЧЕСТВ»

1. 

Внутренняя логика Урока:

Какими же качествами обладает Кришна?

1.  Перечислить 64 качества Кришны, выделив особо 4 последних.
2.  Объяснить чем Кришна превосходит других:

1.  дживы обладают 50 качествами, развитыми в очень незначительной
степени (50 качеств – это 78% от 64 качеств)
2.  Господь Шива наделён 55 качествами, развитыми в значительно большей
степени, чем у джив (55 качеств – это 86% от 64 качеств)
3.  Господь Нараяна наделён 60 качествами, развитыми в бесконечной
степени (60 качеств – это 94% от 64 качеств)
4.  Кришна обладает вышеописанными 60 качествами, проявленными во всём
великолепии, плюс четырьмя особенными качествами, называемыми
«сладостными» (мадхурья)

Вывод: Поскольку Кришна превосходит всех — Он изначальная Личность, Бог,
источник всего сущего, Которого подсознательно ищет каждый.

Действительно ли каждый в материальном мире ищет Кришну? Трудно увидеть
это стремление в жизни человека, желающего иметь хороший дом, красивую
жену, сильное тело и другие материальные блага. Действительно ли это
так?

1.  Стремление к Богу у живого существа, лишённого знания о духовном,
проявляется в его желании быть вечным (Сат), иметь знание (Чит) и быть
счастливым (ананда). Источником этих качеств является Кришна — Он
сат-чит-ананда.

Почему последние четыре качества Кришны названы «сладостными»
(мадхурья)? Что это означает?

Урок №12.

«БЕЗГРАНИЧНОЕ ВЕЛИЧИЕ И СЛАДОСТЬ КРИШНЫ»

Цель урока №12: Укрепить веру слушателя Курса в то, что именно Кришна
является Верховным, объяснив два настроения Кришны – айшварью и
мадхурью.  Другие воплощения Бога могут быть безгранично
величественными, но величие Кришны покрывается Его сладостью. Этим Он
превосходит все другие воплощения.

Внутренняя логика Урока:

Почему последние четыре качества Кришны названы «сладостными»
(мадхурья)? Что это означает?

1.  Описать два настроения Кришны: айшварья — «безграничное величие» и
мадхурья – «безграничная сладость». Показать, что мадхурья превосходит
айшварью.
2.  Именно благодаря последним четырем качествам Кришны, сладость Кришны
проявляется  в безграничной степени (можно обсудить эти 4 качества
Кришны, проиллюстрировав историями).
3.  Кришна в своей изначальной форме никогда не покидает Вриндаван.

Как устроен духовный мир, и в каких формах Господь проявляет Себя там?

1.  Описать основные обители (дхамы) духовного мира и настроения,
которые проявляются там:
2.  По мере того, как проявляется сладость Господа (мадхурья),
ослабевает Его аспект величия (айшварья). Это не означает, однако, что
Господь утрачивает своё величие. Нет, просто сладостный аспект Кришны
скрывает Его величие.
3.  Не осознав величия Кришны, невозможно постичь Его сладостные игры

Почему отношения Господа с Его спутниками во Вриндаване доставляют и
Ему, и им большее счастье, чем на всех других планетах духовного мира?

1.  Отношение к Богу как «безгранично великому» ограничивает
взаимоотношения, ибо осознание величия создает большую дистанцию между
Ним и преданным и мешает проявлению спонтанной любви.
2.  Во Вриндаване между Господом и Его преданными возникают удивительно
близкие, теплые отношения, не ограниченные чувством благоговения и
почтения.

Как человек может постичь Кришну в Его высшей обители? Как достичь этой
обители?

1.  Чтобы достичь Вриндавана — человеку необходима милость Кришны и Его
чистого преданного
2.  В зависимости от того, на каком виде бытия сосредоточен человек,
такого состояния он и достигнет. Поэтому нужно сосредоточиться на имени,
форме, качествах и играх именно Кришны во Вриндаване.
3.  Сначала нужно сосредоточиться на имени, что легче всего сделать,
повторяя харе-кришна-маха-мантру.

У Бога есть много различных имен. Если человек будет повторять другие
имена Бога, то какого результата он при этом достигнет?

Урок №13.

«СЛАДОСТЬ И МОГУЩЕСТВО ХАРЕ-КРИШНА-МАХА-МАНТРЫ»

Цель урока №13: Воодушевить слушателя Курса внимательное повторять
Святое имя, избегая 10 оскорблений. Научить правильно повторять
маха-мантру на практике.

Внутренняя логика Урока:

У Бога есть много различных имен. Если человек будет повторять другие
имена Бога, то какого результата он при этом достигнет?

1.  Перечислить  3 типа Святых имён — второстепенные, главные и
сладостные — и  описать результат, которого человек достигает, повторяя
те или иные имена.
2.  Объяснить, что харе-кришна-маха-мантра обладает особым могуществом:
повторяя её, человек может развить любые отношения с Господом. В ней
заложена сила, позволяющая возвысить человека до Вриндавана — высшей
обители духовного мира.
3.  Чтобы повторение маха-мантры принесло желаемый результат, необходимо
избегать 10 оскорблений.
4.  Невнимательность — причина совершения этих 10 оскорблений.

Что является причиной невнимательности и как её можно преодолеть?

1.  Причина невнимательности — гордость.
2.  Гордость приводит к насилию над другими — в мыслях, словами и
физически. Склонность к насилию существенно уменьшается, если человек
становится вегетарианцем и даже вегетарианскую пищу предлагает Господу.
Также нужно стараться не доставлять беспокойства другим своими словами.
Помня, что насилие зарождается в мыслях, стараться не думать о других
плохо. Всё что случается с нами — это реакция на наши поступки в
прошлом, поэтому никто не виноват в том, что с нами происходит, кроме
нас самих. Поняв это, нужно сознательно избегать насилия.
3.  Тот, кто стал смиреннее соломы, валяющейся на улице, и терпеливее
дерева, кто готов оказывать почтение всем, не ожидая никакого почтения к
себе, может повторять харе-кришна-маха-мантру постоянно.
4.  Таким образом, гордость — это путь к страданиям, а смирение — путь к
подлинному счастью.

Что это за воплощение Кришны — Шри Чайтанья, и почему Его называют Самым
милостивым?

 Урок №14.

«БЕЗГРАНИЧНОЕ ВЕЛИКОДУШИЕ И ЩЕДРОСТЬ

ГОСПОДА ЧАЙТАНЬИ»

Цель урока №14: Воодушевить слушателя Курса взывать к милости Господа
Чайтаньи, как самого милостивого воплощения, и к милости Его спутников
из Панча-таттвы, также находящихся в настроении необычайного великодушия
и щедрости. Обращаясь к их милости можно избавиться от всех ошибок и
оскорблений, которые Вы по неопытности могли совершить.

Внутренняя логика Урока:

Что это за воплощение Кришны — Шри Чайтанья, и почему Его называют Самым
милостивым?

1.  Описать Господа Чайтанью, как особое воплощение Самого Кришны и Его
энергии наслаждения Шримати Радхарани, а также особое настроение Господа
Чайтаньи — аударья.

Когда и с какой целью Шри Чайтанья Махапрабху является в материальном
мире?

1.  Милость Господа Чайтаньи доступна очень редко — один раз в день
Брахмы.
2.  Две цели прихода Господа Чайтаньи:  1. Самому насладиться любовью к
Богу и 2. Раздать эту любовь другим.
3.  Перечислить и описать спутников Господа из Панча-таттвы: Шри
Нитьянанда Прабху (воплощение Баларамы), Его воплощение Шри Адвайта
Прабху (совместное воплощение Маха-Вишну и Сада Шивы), Его внутренняя
энергия Шри Гададхара Прабху (воплощение Шримати Радхарани)  и Его
пограничная энергия Шривас Тхакур.
4.  Господь Чайтанья раскрыл скрытый смысл игр Господа Кришны и
объяснил, как человек может постичь их.
5.  Господь Чайтанья учил всех петь и повторять харе-кришна-маха-мантру
6.  Чтобы избавиться от оскорблений во время повторения Святого имени,
нужно сначала воззвать к милости Панча-таттвы, повторяя
панча-таттва-маха-мантру.

Каждая личность обладает энергией, позволяющей выполнять свои желания и
действовать. Тогда какими же энергиями обладает Кришна?

Урок №15.

«КРИШНА – ОБЛАДАТЕЛЬ ВСЕХ ЭНЕРГИЙ»

Цель урока №15: Описать как благодаря энергиям Кришны возникает всё
творение и воодушевить слушателя Курса стремиться к счастью, которое
доступно во внутренней энергии Господа, или в духовном мире. Высшей
обителью духовного мира является Вриндаван.

Внутренняя логика Урока:

Какими же энергиями обладает Кришна?

1.  Все желания Кришны выполняются Его энергиями.
2.  Его энергии бесчисленны, божественны, вечны и составляют всё сущее.
3.  Энергии Кришны всегда пребывают с Ним, Ему не нужно делать что-либо,
чтобы приобрести их.
4.  И по количеству, и по качественному составу Его энергии бесконечны и
постоянно расширяются. Поэтому их невозможно описать полностью.

Если Его энергии безграничны, как же можно понять их?

1.  Для более ясного понимания Веды подразделяют энергии Кришны на три
основные категории:
2.  В каждой из этих 3-х реальностей присутствуют другие три вида
энергий, о которых уже упоминалось ранее:

1.  Энергия вечности                 (сат, или сандхини).
2.  Энергия знания                 (чит, или самвит).
3.  Энергия блаженства         (ананда, или хладини).

1.  В результате воздействия энергий вечности, знания и блаженства на
внутреннюю, пограничную и внешнюю энергии, возникает все творение
Господа (нарисовать таблицу).

Важный вывод: Для живого существа (дживы) материальные наслаждения
совершенно незначительны (внешняя энергия + энергия наслаждения).
Природа живого существа не незначительна, однако недостаточна
(пограничная энергия + энергия наслаждения). Без соприкосновения с
хладини-шакти во внутренней энергии, живое существо никогда не испытает
абсолютного, безграничного счастья (внутренняя энергия + энергия
наслаждения).

Что из себя представляет Творение Господа?

1.  Описать Творение Господа, показывая схему творения.

Что из себя представляют внешняя, внутренняя и пограничная энергии
Господа?

Урок №16.

«МАТЕРИАЛЬНЫЙ МИР —

ПРОЯВЛЕНИЕ ВНЕШНЕЙ ЭНЕРГИИ КРИШНЫ»

Цель урока №16: Воодушевить слушателя Курса не искать счастья в
материальном мире, ибо оно недостижимо в нём.

Внутренняя логика Урока:

Что собой представляет внешняя энергия? Почему ее называют «внешней»?

1.  Она называется внешней, т.к. качественно отделена от вечно духовного
тела Верховной Божественной Личности, подобно тому, как молоко, являясь
энергией коровы, отделено от неё.

Если материальная энергия является отделенной, означает ли это, что она
независима от Господа?

1.  Хотя материальная энергия и отделена от Него, тем не менее, она
находится под Его управлением и надзором.
2.  Поскольку материальная природа связана с Богом и послушна Его воле,
она называется божественной
3.  Поэтому как бы не пытались люди преодолеть ее влияние, или подчинить
ее своей воле, у них ничего не получится.

А зачем, собственно, человеку нужно преодолевать эту материальную
природу?

1.  Это происходит естественно, поскольку материальный мир чужд природе
живого существа. Он обладает двумя свойствами:

1.  Духкха-алайам — «место страданий»
2.  Ашашватам — «временный»

1.   Поэтому человек сталкивается со страданиями рождения, старости,
болезни, смерти и пр. И даже когда он какое-то время не ощущает на себе
этих страданий, такие минуты быстро заканчиваются, поскольку
материальный мир временен.
2.  «Временный» означает, что все объекты в материальном мире, начиная с
микроскопического уровня и, кончая Вселенским, проходят через три
состояния: сотворение, поддержание и уничтожение.
3.  За внешними, видимыми процессами сотворения, подержания и
уничтожения стоят скрытые, тонкие силы, которые называются гунами
материальной природы.

Что это за силы, гуны материальной природы, как они проявляются и каково
их влияние на человека?

Урок №17.

«ТРИ ГУНЫ МАТЕРИАЛЬНОЙ ПРИРОДЫ»

Цель урока №17: Объяснить слушателю Курса как проявляются гуны
материальной природы и как, связывая человека, они приводят его к
деградации. Пробудить у слушателя Курса желание освободиться от влияния
гун.

Внутренняя логика Урока:

Что это за силы, гуны материальной природы, как они проявляются и каково
их влияние на человека?

1.  Существует три гуны: благость, страсть и невежество.
2.  Весь материальный мир является порождением трёх гун, которые,
смешиваясь между собой, порождают огромный спектр различных сочетаний,
подобно трём цветам, смешиваемым в различных пропорциях.
3.  Люди, не имеющие знания о трёх гунах, видят это огромное
разнообразие, не замечая стоящих за ним гун, и поэтому попадают под их
влияние.

Каким же образом материальная природа обуславливает живое существо?

1.  Материальная природа делает это, используя два вида энергий: 1.
пракшепатмика-шакти — стягивающая энергия, и 2. аваранатмика-шакти —
покрывающая энергия.
2.  Объяснить на примере рыбы, как материальная энергия порабощает живое
существо.

Как понять, что за гуны материальной природы влияют на человека?

1.  Признаки гуны благости: 1) Она чище других гун, 2) она просветляет
или дает знание, 3) Она избавляет от всех последствий грехов. Однако
из-за привязанности к знанию и к счастью в сознание такого человека
проникает гуна страсти.
2.  Признаки гуны страсти: 1) Бесконечные желания, 2) Алчность. Из-за
них человек вовлекается в бурную деятельность и привязывается к ней и к
ее плодам. В результате накапливаются усталость и беспокойство, и, чтобы
освободиться от них, человек прибегает к алкоголю, наркотикам и т.п. Так
в его сознание постепенно проникает гуна невежества.
3.  Признаки гуны невежества: 1) Она держит воплощенные живые существа в
иллюзии. В результате влияния иллюзии человек становится безумным,
ленивым и сонным. Гуна невежество постепенно опускает человека до адских
условий жизни.

Важный вывод: Если человек не прилагает сознательных усилий чтобы
возвышать своё сознание и лишь «просто живёт», он неминуемо вынужден
будет деградировать, опускаясь всё ниже и ниже. Деградация же всегда
сопровождается ощущением неудовлетворённости и несчастья.

Как же можно преодолеть влияние гун материальной природы?

Урок №18.

«ВОЗВЫШЕНИЕ НАД ГУНАМИ СТРАСТИ И НЕВЕЖЕСТВА»

Цель урока №18: Объяснить слушателю Курса, как важно общаться с
преданными и жить в гуне благости для того, чтобы освободиться от
влияния сначала низших гун страсти и невежества, а затем и от влияния
гуны благости.

Внутренняя логика Урока:

Как же можно преодолеть влияние гун материальной природы?

1.  Первое важное условие — необходимо иметь возможность общения со
старшим преданным. Поскольку гуны связаны с материальным разумом, то,
только изменив разум, благодаря общению с преданными и духовному
обучению, можно изменить влияние гун и, в конце концов, вообще
избавиться от их влияния.
2.  Второе важное условие: Черпая энтузиазм в общении с преданными,
человеку сначала нужно развить в себе качества благости. Для этого он
должен:

1.  Знать закон: сосредоточившись на гуне благости, я усиливаю её
влияние, и т.о. гуны невежества и страсти вытесняются из сознания.
2.  Знать что: чтобы усилить влияние благости нужно сознательно
прилагать усилия, чтобы жить в благости.

Важный вывод: Если Вы, используя свою свободу выбора,  выберете
определенную сферу своего существования либо в благости, либо в страсти,
либо в невежестве, то Вы обязательно получите результат, приносимый
влиянием этой конкретной гуны материальной природы.

Как же человек может преодолеть влияние гуны благости и достичь
духовного уровня существования?

Урок №19.

«ВОЗВЫШЕНИЕ НАД ГУНОЙ БЛАГОСТИ»

Цель урока №19: Объяснить слушателю Курса как благодаря практике
преданного служения человек может освободиться от влияния ложного эго и
так, осознав себя слугой Господа, преодолеть влияние гун.

Внутренняя логика Урока:

Как же человек может преодолеть влияние гуны благости и достичь
духовного уровня существования?

1.  Третье важное условие – Чтобы избавиться от влияния даже
материальной гуны благости, нужно развить в себе качества, присущие
трансцендентной благости (вишуддха-саттве). Для этого нужно, живя в гуне
благости, выполнять все свои обязанности (материальные и духовные) как
подношение Кришне. Так постепенно человек может обрести вкус действовать
в настроении слуги Господа и избавляется от ложного эго («Я» и «Моё»),
обретя истинное эго («Я — слуга», «Кришна — Мой Господин»).

Каково предназначение материального мира? Кто является высшей причиной
сотворения материального мира?

Урок №20.

«КРИШНА — ВЫСШАЯ ПРИЧИНА СОТВОРЕНИЯ МАТЕРИАЛЬНОГО МИРА»

Цель урока №20: Объяснить, что именно Кришна является конечной причиной
создания материального мира и что Он творит его для того, чтобы помочь
живому существу развить утраченную любовь к Нему и вернуться в своё
изначальное положение в духовном мире.

Внутренняя логика Урока:

Каково предназначение материального мира? Кто является высшей причиной
сотворения материального мира?

1.  Материальный мир создается с двумя целями:

1.  Предоставить возможность живому существу наслаждаться отдельно от
Господа.
2.  Предоставить возможность живому существу вернуться в свое
изначальное положение в духовном мире.

1.  Главная цель — вторая.

Кто является высшей причиной сотворения материального мира?

1.  Высшей причиной сотворения материального мира является Кришна, Он
делает это при помощи Своих особых воплощений.

В какой  из Своих многочисленных форм Кришна осуществляет Творение?

1.  Кришна осуществляет материальное Творение при помощи трёх Своих
особых воплощений — пуруша-аватар:

1.  Маха-Вишну
2.  Гарбходакашайи Вишну
3.  Кширодакашайи Вишну

Каковы основные этапы творения материального мира?

1.  Сарга — первичное творение, осуществляемое Господом Вишну.
2.  Висарга — вторичное творение, осуществляемое Брахмой.

Как Господь осуществляет первичное Творение?

Урок №21.

«ВЗГЛЯД МАХА-ВИШНУ»

Цель урока №21: Дать слушателю Курса понимание того, что Творение
происходит не само по себе, а благодаря энергии взгляда Господа
Маха-Вишну. Поэтому именно Он является первопричиной материального
мироздания. Но причина всех причин — Господь Кришна, Верховная
Божественная Личность.

Внутренняя логика Урока:

Как Господь осуществляет первичное Творение?

1.  Маха-Вишну бросает взгляд на прадхану — «инертную материальную
энергию» и приводит её в активное состояние. Активизированная взглядом
Маха-Вишну материальная природа называется махат-таттва.

Что же собой представляет этот взгляд Маха-Вишну, благодаря которому
инертная материальная энергия так активизируется?

1.  Взгляд Господа Маха-Вишну содержит в себе:

1.  изначальное мужское начало (Шамбху, или Шива).
2.  энергию вечного времени (кала)
3.  всех тех живых существ, которым предстоит воплотиться в материи
(джива)

Важный вывод: Благодаря взгляду Маха-Вишну три гуны материальной природы
приходят в активное состояние и дживы, живые существа которым предстоит
воплотиться в материи, попадают в махат-таттву. Поскольку живые
существа, попавшие в махат-таттву, приносят с собой эгоистическое
желание наслаждаться отдельно от Кришны, их покрывает первый
материальный элемент, ложное эго, проявляясь в махат-таттве под влиянием
энергии времени. Затем ложное эго, в сочетании с тремя гунами, проявляет
все составляющие материальные элементы будущего Творения. Поэтому именно
эгоистическое желание живых существ наслаждаться отдельно от Кришны
является коренной причиной возникновения всего материального Творения.

Какие материальные первоэлементы возникают в результате соприкосновения
ложного эго с тремя гунами материальной природы?

Урок №22.

«ТВОРЕНИЕ МАТЕРИАЛЬНОГО МИРА»

Цель урока №22: Дать слушателю Курса представление о том, как
разворачивается материальное Творение и помочь ему увидеть, каким
образом из Кришны,  причины всех причин, появляются все последующие
причины.

Внутренняя логика Урока:

Какие материальные первоэлементы возникают в результате соприкосновения
ложного эго с тремя гунами материальной природы?

1.  ложное эго, в сочетании с тремя гунами, трансформируется в три вида:

1.  Вайкарика        – ложное эго в гуне благости
2.  Тайджаса        – ложное эго в гуне страсти
3.  Тамаса        – ложное эго в гуне невежества

1.  Вайкарика: В результате трансформации ложного эго в гуне благости
возникает материальный ум и  принцип полубогов, управляющих
деятельностью тела.
2.  Тайджаса: В результате трансформации ложного эго в гуне страсти
возникает интеллект (разум), прана, пять действующих (кармендрийа) и
пять познающих чувств (гьянендрийа). Действующие чувства связаны с
праной, а познающие — с разумом.

Важный вывод: Человек, находящийся под влиянием гуны страсти, пытается
выстоять в борьбе за существование, задействовав свой разум и жизненную
энергию, а также познающие и действующие чувства. Всё это деятельность в
гуне страсти, истощающая энергию человека. Результат, который она
приносит, уже описывался в уроке № 18. Но те, кто стремятся к духовному
прогрессу, должны полностью избавиться от влияния гуны страсти и достичь
уровня гуны благости. Действуя в благости, человек также получит всё
необходимое для жизни, а также результат, который приносит гуна
благости, и, затем, возможность возвыситься до духовного мира.

1.  Тамаса: В результате трансформации ложного эго в гуне невежества,
возникают пять материальных элементов (эфир, воздух, огонь, вода,
земля), пять объектов этих элементов (звук, касание, форма, вкус, запах)
и пять органов для их восприятия (ухо, кожа (орган осязания), глаз, язык
и нос).
2.  Процесс создания грубых элементов, их объектов и органов восприятия
начинается с более тонких и развивается к более грубым.
3.  Каждый последующий материальный элемент сохраняет качества
предыдущего:

1.  Эфир         – звук
2.  Воздух         – звук, касание
3.  Огонь         – звук, касание, форма
4.  Вода        – звук, касание, форма, вкус
5.  Земля         – звук, касание, форма, вкус, запах

1.  Так, исследуя качества различных элементов, проницательный человек
может увидеть причину их появления:

причиной появления земли является вода, причиной воды —  огонь, причиной
огня — воздух, причиной воздуха — эфир, причиной эфира — звук, а
причиной звука — эго в гуне невежества (тамаса). Эго в гуне невежества
возникает благодаря взгляду Маха-Вишну, посредством которого три гуны
материальной природы активизируются, и живые существа появляются в
махат-таттве. Причина появления Маха-Вишну — Санкаршана-2, причина
Санкаршаны-2 — Господь Нараяна, причина Нараяны — Санкаршана-1, причина
Санкаршаны-1 — Баларама, а причина Баларамы — Господь Кришна, Верховная
Божественная Личность. Поэтому Кришна является причиной всех причин.

1.  Материальное Творение возможно только благодаря присутствию высшей
воли, воли Бога. Без Его воли материальные элементы не способны
соединиться вместе, не говоря уже о том, чтобы иметь определённое
предназначение.

Как осуществляется вторичное творение — висарга?

1.  Далее Господь Брахма (первое живое существо во вселенной),
наделённый особыми полномочиями соединять материальные первоэлементы в
разнообразные формы, осуществляет вторичный этап творения. Он медитирует
на духовные звуки, олицетворяющие собой духовные формы и, видя эти
формы, творит по их подобию и на их основе материальные формы. Так
появляются все материальные планеты и 8400000 форм жизни.

Как во вселенной проявляется время?

Урок №23.

«ХОД ВРЕМЕНИ ВО ВСЕЛЕННОЙ»

Цель урока №23: Дать слушателю Курса понимание того, как время
проявляется во вселенной, постепенно разрушая её. Воодушевить его тем,
что в этот век Кали существует особая возможность обрести милость
Господа Чайтаньи через пение харе-кришна-маха-мантры в обществе
преданных. Легче всего это делать в рамках малой группы, называемой
«бхакти-врикша».

Внутренняя логика Урока:

Как проявляется время во вселенной?

1.  время является безличным проявлением Кришны во вселенной и поэтому
во влиянии времени проявляется Его воля и власть.
2.  Время порождает в живом существе, находящемся под влиянием ложного
эго, страх смерти.

Каковы еще функции времени?

1.  Все объекты в материальном мироздании проходят через три
принципиальных этапа:

1.  Творения
2.  Поддержания
3.  Разрушения

1.  Время также проявляется в трех фазах:

1.  Прошлое
2.  Настоящее
3.  Будущее

Какова продолжительность существования вселенной?

1.  Продолжительность существования вселенной равна жизни Брахмы
(викалпа) или 311 040 000 000 000 лет.
2.  Жизнь Брахмы делится на 100 лет, каждый год на 12 месяцев, а каждый
месяц на 30 суток. Каждые сутки делятся на две равные части: ночь и
день.
3.  День Брахмы (калпа), так же, как и его ночь, равен 4 320 000 000 лет
и делится на тысячу дивья-юг, каждая из которых равна 4 320 000 лет.
4.  Каждая дивья-юга состоит из четырёх эпох: Сатья (1.728.000 лет),
Трета (1.296.000 лет), Двапара (864.000 лет) и Кали (432.000 лет). В
настоящее время идёт эпоха Кали, с начала которой прошло чуть более 5000
лет.

Задание: Рассчитать сколько земных лет пройдёт в течение 1 секунды
Брахмы (ответ — 100.000 лет).

Какова продолжительность жизни людей, живущих в Сатья-, Трета-, Двапара-
и Кали-юги? Чем отличается их образ жизни?

1.  Описать образ жизни людей разных эпох, продолжительность их жизни,
уровень добродетели и метод духовной практики. Нарисовать таблицу.
2.  Описать преимущества  «Золотого века» в эту Кали-югу.
3.  Подчеркнуть важность участия во встречах групп «бхакти-врикша» и
вдохновить слушателя Курса присоединиться к ней.

Какие виды взаимоотношений возможны с Богом?

Урок №24.

«КРИШНА — ЦЕНТР ВСЕХ ДУХОВНЫХ ВЗАИМООТНОШЕНИЙ»

Цель урока №24: Описать духовный мир, сущностью которого являются
духовные расы и то, как раса развивается. Подчеркнуть отличие
материальных отношений от духовных.

Внутренняя логика Урока:

Какие виды взаимоотношений возможны с Богом?

1.  Хотя все эти отношения неповторимы, тем не менее, их можно
подразделить на 5 основных видов:

1.  Шанта-раса        – нейтральные отношения
2.  Дасья-раса                – отношения служения
3.  Сакхья-раса        – дружеские отношения
4.  Ватсалья-раса        – родительские отношения
5.  Мадхурья раса        – супружеские отношения

1.  Помимо этих пяти, существует еще семь второстепенных видов
взаимоотношений, которые усиливают основные:

1.  Хасья                – смех
2.  Адбхута                – удивление
3.  Вира                – рыцарство
4.  Каруна                – милость, сострадание
5.  Раудра                – гнев
6.  Бхайянака                – ужас, страх
7.  Бибхатса                – потрясение, отвращение

Как понять какие отношения у меня с Кришной и как эти отношения
развиваются?

1.  Необходимо очистить своё сознание, и тогда эти отношения проявятся
сами собой.
2.  Взаимоотношения развиваются постепенно (нарисовать таблицу).

Важный вывод: Таким образом, семя Ваших вечных взаимоотношений с Кришной
уже есть у Вас в сердце. Если Вы будете поливать это семя водой практики
слушания и повторения харе-кришна-маха-мантры и повествований об имени,
форме, качествах и играх Кришны, тогда эти отношения проявятся — в
должный срок.

В духовном мире есть множество планет. Какие виды взаимоотношений живых
существ с Богом проявляются на этих планетах?

1.  Описать, нарисовав рисунок.

Важный вывод: Хотя внешне духовные отношения напоминают отношения живых
существ в материальном мире, они имеют совершенно иную природу. Поэтому
ни в коем случае нельзя оценивать духовные взаимоотношения на основе
своего материального опыта.

Каково отличие материального мира от духовного мира, и материальных
отношений от духовных?

Урок №25.

«СРАВНЕНИЕ ДУХОВНОГО И МАТЕРИАЛЬНОГО МИРОВ»

Цель урока №25: Сравнить духовный и материальный миры, а также духовные
и материальные взаимоотношения, чтобы понять их отличие и сделать
правильный выбор в следующем уроке.

Внутренняя логика Урока:

Каково отличие материального мира от духовного мира, и материальных
отношений от духовных?

1.  Материальный мир является зеркальным отражением духовного мира —
отражаются, прежде всего, расы. Сами материальный и духовный миры
являются лишь подходящими подмостками, на которых эти взаимоотношения
разыгрываются.
2.  Кама и према отличаются так же, как железо и золото.
3.  Нарисовать схему:

шанта-раса
----------

шанта-раса
лже-шанта-раса

лже-дасья-раса

лже-сакхья-раса

лже-ватсалья-раса

лже-мадхурья-раса
